
# Cohesive DuckDB Analysis Notebook

### Notebook goals
1. Profile the three core tables and confirm schema assumptions.
2. Quantify data quality issues before building interpretations.
3. Connect engagement activity to technology adoption signals.
4. Investigate anomalies and "weird" patterns worth deeper follow-up.
5. Set up segmentation, feature engineering, and downstream modeling.

### Project framing
The kickoff emphasized that the business question is not just increasing interaction counts, but understanding whether engagement leads to meaningful technology adoption. The requested deliverables include developer cohort profiles, asset impact analysis, a data enrichment plan, and a repeatable framework for future monitoring.


## 1. Environment setup
Update the database path below if your local file lives elsewhere.

In [2]:

import duckdb
import pandas as pd

DB_PATH = "developer_project.duckdb"
con = duckdb.connect(DB_PATH)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 100)


## 2. Table inventory and quick orientation
Start by confirming the tables available in the working database.

In [3]:
con.execute("SHOW TABLES").fetchdf()

                                      name
0                          activity_capped
1                           activity_clean
2                           activity_final
3                             activity_raw
4                          activity_sample
5                    activity_score_bounds
6             activity_score_mapping_clean
7               activity_score_mapping_raw
8                          activity_scored
9                           activity_stage
10                   activity_standardized
11                  activity_user_features
12                           contact_clean
13  contact_clean_backup_before_supplement
14                           contact_final
15                             contact_raw
16                          contact_sample
17                           contact_stage
18                contact_supplement_clean
19                  contact_supplement_raw
20                  developer_feature_base
21                      sdk_download_clean
22                      sdk_download_final
23                        sdk_download_raw
24                     sdk_download_sample


## 3. Project hypotheses to test
These hypotheses help connect descriptive analysis to the final deliverables.

- Highly engaged developers are more likely to show downstream adoption signals.
- Some developers may adopt technology without passing through high-touch engagement assets.
- Activity counts alone may overstate impact if repeated or low-value interactions dominate the data.
- Geography, organization quality, and source-system inconsistencies may distort segmentation unless addressed.

## 4. Current baseline analysis already completed

### Activity table baseline

In [4]:

con.execute("SELECT COUNT(*) AS row_count FROM activity_clean").fetchdf()

   row_count
0   69347526

In [5]:

con.execute("SELECT * FROM activity_raw LIMIT 30").fetchdf()

,activity,activity_date,activity_name,activity_type,activity_role,activity_attendance,dev_contact,activity_score,filepath,activity_id,pk1,pk2,lead_source,nvidia_campaign_id,gtc_nvidia_campaign_id,lead_source_details
0,DLI Training,2025-11-12T06:39:30.000Z,Building RAG Agents with LLMs,Instructor-Led,Attendee,Attended Live,6417584,40.0,None,1875418,1875418,course-v1:DLI+S-FX-15+V1-ZH,None,None,None,None
1,DLI Training,2024-05-18T15:53:18.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,6752524,20.0,None,764222,764222,course-v1:DLI+S-FX-01+V1,None,None,None,None
2,DLI Training,2024-04-17T09:30:35.000Z,(COURSE ENDING ON 7/1/24) High-Performance Com...,Self-Paced Online,Attendee,Attended Live,6389272,20.0,None,736857,736857,course-v1:DLI+L-AC-25+V1-ZH,None,None,None,None
3,DLI Training,2024-05-22T11:40:34.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,6763105,20.0,None,766590,766590,course-v1:DLI+S-FX-01+V1,None,None,None,None
4,DLI Training,2024-05-30T08:31:34.000Z,Prompt Engineering with LLaMA-2 (Access Expire...,Self-Paced Online,Attendee,Attended Live,6790671,20.0,None,774705,774705,course-v1:DLI+S-FX-12+V1,None,None,None,None
5,DLI Training,2024-05-28T21:17:51.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,6784220,20.0,None,772702,772702,course-v1:DLI+S-FX-01+V1,None,None,None,None
6,DLI Training,2024-06-19T01:55:54.000Z,Augment your LLM Using Retrieval Augmented Gen...,Self-Paced Online,Attendee,Attended Live,6878366,20.0,None,798402,798402,course-v1:DLI+S-FX-16+V1,None,None,None,None
7,DLI Training,2021-05-13T03:36:16.000Z,Data Augmentation and Segmentation with Genera...,Self-Paced Online,Attendee,Attended Live,1257703,20.0,None,307474,307474,course-v1:DLI+L-HX-09+V1-ZH,None,None,None,None
8,DLI Training,2024-06-19T03:30:41.000Z,Modeling Time Series Data with Recurrent Neura...,Self-Paced Online,Attendee,Attended Live,6878674,20.0,None,798483,798483,course-v1:DLI+L-FX-24+V1,None,None,None,None
9,DLI Training,2024-05-29T05:01:50.000Z,Building Real-Time Video AI Applications,Self-Paced Online,Attendee,Attended Live,6785420,20.0,None,773063,773063,course-v1:DLI+S-IV-01+V1,None,None,None,None
10,DLI Training,2024-04-18T16:35:45.000Z,Accelerating End-to-End Data Science Workflows...,Self-Paced Online,Attendee,Attended Live,2107115,20.0,None,738300,738300,course-v1:DLI+S-DS-01+V1,None,None,None,None
11,DLI Training,2023-12-14T15:37:07.000Z,Generative AI with Diffusion Models,Self-Paced Online,Attendee,Attended Live,5898702,20.0,None,599160,599160,course-v1:DLI+S-FX-14+V1,None,None,None,None
12,DLI Training,2024-05-10T09:28:45.000Z,[Access Expires 03/16/2026]Getting Started wit...,Self-Paced Online,Attendee,Attended Live,6726647,20.0,None,757413,757413,course-v1:DLI+S-AC-04+V1,None,None,None,None
13,DLI Training,2024-05-10T13:19:18.000Z,Fundamentals of Accelerated Computing with CUD...,Self-Paced Online,Attendee,Attended Live,6727357,20.0,None,757616,757616,course-v1:DLI+S-AC-10+V1,None,None,None,None
14,DLI Training,2020-08-05T20:08:19.000Z,Fundamentals of Accelerated Computing with CUD...,Self-Paced Online,Attendee,Attended Live,78294,20.0,None,257212,257212,course-v1:DLI+C-AC-01+V1,None,None,None,None
15,DLI Training,2020-12-31T11:10:31.000Z,Fundamentals of Accelerated Computing with CUD...,Self-Paced Online,Attendee,Attended Live,2830024,20.0,None,283987,283987,course-v1:DLI+C-AC-01+V1,None,None,None,None
16,DLI Training,2024-04-19T10:01:57.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,6619368,20.0,None,739040,739040,course-v1:DLI+S-FX-01+V1,None,None,None,None
17,DLI Training,2025-05-27T18:17:59.000Z,A Beginner's Guide to Autonomous Robots,Self-Paced Online,Attendee,Attended Live,8956961,20.0,None,1493366,1493366,course-v1:DLI+S-OV-35+V1,None,None,None,None
18,DLI Training,2022-04-26T20:20:34.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,4465093,20.0,None,410514,410514,course-v1:DLI+S-FX-01+V1,None,None,None,None
19,DLI Training,2024-05-26T18:04:15.000Z,[Access Expires 03/16/2026]Getting Started wit...,Self-Paced Online,Attendee,Attended Live,6776717,20.0,None,770602,770602,course-v1:DLI+S-AC-04+V1,None,None,None,None
20,DLI Training,2024-08-10T14:31:20.000Z,Integrating Sensors with NVIDIA DRIVE®,Self-Paced Online,Attendee,Attended Live,7080178,20.0,None,861204,861204,course-v1:DLI+S-AV-06+V1,None,None,None,None
21,DLI Training,2024-06-20T18:15:23.000Z,Introduction to Graph Neural Networks,Self-Paced Online,Attendee,Attended Live,3037476,20.0,None,800552,800552,course-v1:DLI+S-FX-05+V1,None,None,None,None
22,DLI Training,2024-07-27T08:08:10.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,7026289,20.0,None,841403,841403,course-v1:DLI+S-FX-01+V1,None,None,None,None
23,DLI Training,2025-05-28T04:38:01.000Z,Generative AI with Diffusion Models,Self-Paced Online,Attendee,Attended Live,8958562,20.0,None,1494127,1494127,course-v1:DLI+S-FX-14+V1,None,None,None,None
24,DLI Training,2025-05-28T05:54:43.000Z,Augment your LLM Using Retrieval Augmented Gen...,Self-Paced Online,Attendee,Attended Live,8906549,20.0,None,1494323,1494323,course-v1:DLI+S-FX-16+V1,None,None,None,None
25,DLI Training,2024-07-11T03:37:42.000Z,Modeling Time Series Data with Recurrent Neura...,Self-Paced Online,Attendee,Attended Live,6962400,20.0,None,821993,821993,course-v1:DLI+L-FX-24+V1,None,None,None,None
26,DLI Training,2024-06-22T03:10:51.000Z,Modeling Time Series Data with Recurrent Neura...,Self-Paced Online,Attendee,Attended Live,6891390,20.0,None,801781,801781,course-v1:DLI+L-FX-24+V1,None,None,None,None
27,DLI Training,2024-06-03T11:04:28.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,6112415,20.0,None,777879,777879,course-v1:DLI+S-FX-01+V1,None,None,None,None
28,DLI Training,2024-06-03T14:13:07.000Z,Prompt Engineering with LLaMA-2 (Access Expire...,Self-Paced Online,Attendee,Attended Live,6803979,20.0,None,778067,778067,course-v1:DLI+S-FX-12+V1,None,None,None,None
29,DLI Training,2024-08-05T14:10:25.000Z,Getting Started with Deep Learning,Self-Paced Online,Attendee,Attended Live,812400,20.0,None,852796,852796,course-v1:DLI+S-FX-01+V1,None,None,None,None

In [6]:

con.execute("""
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'activity_clean'
ORDER BY ordinal_position
""").fetchdf()

               column_name
0              dev_contact
1                 activity
2            activity_name
3            activity_type
4            activity_role
5      activity_attendance
6           activity_score
7            activity_date
8              activity_id
9                 filepath
10                     pk1
11                     pk2
12             lead_source
13      nvidia_campaign_id
14  gtc_nvidia_campaign_id
15     lead_source_details

In [7]:

con.execute("SUMMARIZE activity_clean").fetchdf()

100% ▕██████████████████████████████████████▏ (00:00:02.66 elapsed)

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,dev_contact,VARCHAR,0003027cbcc9f926a435232e311b3a5ffcbb0d16668d12...,fffa9af220d19ab1ad50f0d2b1af409e4b0b0f732481d4...,6971468,NaN,NaN,NaN,NaN,NaN,69347526,0.00
1,activity,VARCHAR,Brev,"timeout-in-us = 4096 * (2**timeout)""",21,NaN,NaN,NaN,NaN,NaN,69347526,0.00
2,activity_name,VARCHAR,(COURSE ENDING ON 7/1/24) High-Performance Com...,（同時通訳付）Unlocking the Power of Agentic AI: Effe...,247536,NaN,NaN,NaN,NaN,NaN,69347526,7.12
3,activity_type,VARCHAR,API Catalog Hosted API,true,59,NaN,NaN,NaN,NaN,NaN,69347526,0.00
4,activity_role,VARCHAR,*Showstopper*,VivaTech Attendee,40,NaN,NaN,NaN,NaN,NaN,69347526,13.20
5,activity_attendance,VARCHAR,15,true,24,NaN,NaN,NaN,NaN,NaN,69347526,81.36
6,activity_score,DOUBLE,0.0,949763.0,16,3.4864210675072056,198.7994155581355,1.4549214275818465,3.0,3.0,69347526,1.31
7,activity_date,TIMESTAMP,2020-01-01 00:00:00,2026-03-12 17:24:45,10083528,2023-07-29 09:29:58.041171,NaN,2021-12-22 17:27:48.381268,2023-10-15 12:04:18.438245,2025-04-04 02:59:06.792796,69347526,0.00
8,activity_id,VARCHAR,--06jdo1meBBcl3t43Bw8twy5qo4b-WOFu9r_NPZ5JQ_20...,zzzKQIQtKhEv-aG9Dqw60fJX5IV8Rr8rrCGRIWBmS50_20...,51295433,NaN,NaN,NaN,NaN,NaN,69347526,0.00
9,filepath,VARCHAR,!git clone https://github.com/NVIDIA-AI-Bluepr...,zwn4k2csbt9r/nvcf/punctuation-riva,210473,NaN,NaN,NaN,NaN,NaN,69347526,22.16
10,pk1,VARCHAR,--06jdo1meBBcl3t43Bw8twy5qo4b-WOFu9r_NPZ5JQ_20...,zzzKQIQtKhEv-aG9Dqw60fJX5IV8Rr8rrCGRIWBmS50_20...,51295433,NaN,NaN,NaN,NaN,NaN,69347526,0.00
11,pk2,VARCHAR,0000041377580f8fc27178c22a964725,zzr7dxtb,368697,NaN,NaN,NaN,NaN,NaN,69347526,0.17
12,lead_source,VARCHAR,$direct,yseo,529,NaN,NaN,NaN,NaN,NaN,69347526,82.81
13,nvidia_campaign_id,VARCHAR,%20%20%20em-even-981938-hats3th_vi_na_all_s4%2...,—43656,26733,NaN,NaN,NaN,NaN,NaN,69347526,98.99
14,gtc_nvidia_campaign_id,VARCHAR,em-anno-951875,so-medi-691956,46,NaN,NaN,NaN,NaN,NaN,69347526,100.00
15,lead_source_details,VARCHAR,%22NVODIA+developer%22,zhidao.baidu.com/question/49345313.html?fr=iks...,177729,NaN,NaN,NaN,NaN,NaN,69347526,84.02

### Contacts table baseline

In [8]:

con.execute("SELECT COUNT(*) AS row_count FROM contact_clean").fetchdf()

   row_count
0    9381490

In [9]:

con.execute("SELECT * FROM contact_raw LIMIT 30").fetchdf()

,developer_id,program_application_source,country,region,sub_region,zone,territory,organization_english_name,development_areas,other_development_areas,industry_segment_vertical,other_industry_segment_vertical,sub_industry_segment_vertical,fields_of_interest,other_fields_of_interest,first_program_application_date,account_id,account_name,last_activity_date,last_modified_date,created_date,wwfo_category,wwfo_target_list,account_industry_segment,account_source,account_type,devzone_last_login_date,organization_website,inception_id,first_activity_date,normalized_account_name,rdp_exit_date
0,9828293,dli,India,APAC,India,India,SOUTH ASIA,L&T Technology Services,Agentic AI / Generative AI;Data Science;Roboti...,null,AEC,null,null,null,null,2025-11-25T09:30:05.000Z,5768,L&T Technology Services,2025-11-25T09:32:29.000Z,2025-12-02T01:09:00.689Z,2025-11-25T09:30:05.200Z,null,null,null,Leadspace;GSI;NV Top 1000 Ent,Enterprise,null,ltts.com,null,2025-11-25T09:30:05.000Z,L&T Technology Services,null
1,9828383,dli,India,APAC,India,India,SOUTH ASIA,L&T Technology Services,Agentic AI / Generative AI;Data Science;Data C...,null,Automotive / Transportation,null,null,null,null,2025-11-25T09:41:30.000Z,5768,L&T Technology Services,2025-11-25T09:44:40.000Z,2025-12-10T01:09:46.643Z,2025-11-25T09:41:29.029Z,null,null,null,Leadspace;GSI;NV Top 1000 Ent,Enterprise,null,ltts.com,null,2025-11-25T09:41:30.000Z,L&T Technology Services,null
2,9828681,devzone,India,APAC,India,India,SOUTH ASIA,Dayananda Sagar Universiry,Agentic AI / Generative AI;AR / VR;Simulation ...,null,Other,null,null,null,null,2025-11-25T10:39:42.000Z,31153,Not Normalized,2026-03-10T00:00:00.000Z,2026-03-10T05:24:58.708Z,2025-11-25T10:39:42.694Z,null,null,null,Manual,NaN,2026-03-09T22:22:32.000Z,null,null,2025-11-25T00:00:00.000Z,Not Normalized,null
3,9829013,dli,India,APAC,India,India,SOUTH ASIA,LTTS,Developer Tools & Techniques;Agentic AI / Gene...,null,Other,null,null,null,null,2025-11-25T11:24:35.000Z,31153,Not Normalized,2025-11-27T12:29:09.000Z,2025-12-13T01:09:06.304Z,2025-11-25T11:24:33.415Z,null,null,null,Manual,NaN,null,null,null,2025-11-25T11:24:35.000Z,Not Normalized,null
4,9829125,devzone,India,APAC,India,India,SOUTH ASIA,Hexaware,Agentic AI / Generative AI;Data Center / Cloud,null,Cloud Services,null,null,null,null,2025-11-25T11:34:05.000Z,31153,Not Normalized,2025-12-04T12:27:20.000Z,2025-12-05T19:08:39.644Z,2025-11-25T11:34:04.830Z,null,null,null,Manual,NaN,2025-12-01T06:12:14.000Z,null,null,2025-11-25T11:34:05.000Z,Not Normalized,null
5,9829190,dli,India,APAC,India,India,SOUTH ASIA,L&T Technology Services,Agentic AI / Generative AI,null,Smart Cities / Spaces,null,null,null,null,2025-11-25T11:46:56.000Z,5768,L&T Technology Services,2025-12-03T10:09:20.000Z,2025-12-16T01:08:48.701Z,2025-11-25T11:46:56.248Z,null,null,null,Leadspace;GSI;NV Top 1000 Ent,Enterprise,null,ltts.com,null,2025-11-25T11:46:56.000Z,L&T Technology Services,null
6,9831912,dli,India,APAC,India,India,SOUTH ASIA,LTTS,Agentic AI / Generative AI,null,Other,null,null,null,null,2025-11-26T01:34:57.000Z,31153,Not Normalized,2025-12-01T02:38:25.000Z,2025-12-09T01:09:57.915Z,2025-11-26T01:34:56.652Z,null,null,null,Manual,NaN,null,null,null,2025-11-26T01:34:57.000Z,Not Normalized,null
7,9832663,null,India,APAC,India,India,SOUTH ASIA,Nokia,null,null,Other,null,null,null,null,null,2732,Nokia,2025-12-10T00:00:00.000Z,2025-12-10T18:16:17.016Z,2025-11-26T05:22:12.467Z,Telecommunications,SuperPOD 2019_P1,null,Fortune 500: 2020;WWFO; Fortune 500: 2021;Telc...,Enterprise,null,nokia.com,null,2025-12-10T00:00:00.000Z,Nokia,null
8,9833472,dli,India,APAC,India,India,SOUTH ASIA,MLRIT,Trustworthy AI / Cybersecurity;Data Science;Ag...,null,Academia / Education,null,null,null,null,2025-11-26T08:05:31.000Z,3297,Mlrit,2025-11-26T08:05:46.000Z,2025-11-27T01:09:11.830Z,2025-11-26T08:05:29.338Z,null,null,null,Leadspace,NaN,null,mlrit.ac.in,null,2025-11-26T08:05:31.000Z,Mlrit,null
9,9836934,dli,India,APAC,India,India,SOUTH ASIA,Tejas Networks,Trustworthy AI / Cybersecurity;Data Science;Ne...,null,Telecommunications,null,null,null,null,2025-11-27T02:03:26.000Z,31153,Not Normalized,2025-11-27T02:07:13.000Z,2025-11-28T02:08:42.492Z,2025-11-27T02:03:26.275Z,null,null,null,Manual,NaN,null,null,null,2025-11-27T02:03:26.000Z,Not Normalized,null
10,9837489,dli,India,APAC,India,India,SOUTH ASIA,Harman International Industries,Trustworthy AI / Cybersecurity;Data Science;Ne...,null,Healthcare & Life Sciences,null,null,null,null,2025-11-27T04:56:52.000Z,7763,Harman International Industries,2025-11-27T04:57:06.000Z,2025-11-27T07:09:38.800Z,2025-11-27T04:56:52.032Z,null,null,null,Fortune500;NV Top 1000 Ent,Enterprise,null,harman.com,null,2025-11-27T04:56:52.000Z,Harman International Industries,null
11,9837558,devzone,India,APAC,India,India,SOUTH ASIA,ANNA UNIVERSITY,Agentic AI / Generative AI;Robotics;Computer V...,null,Academia / Education,null,null,null,null,2025-11-27T05:29:15.000Z,2776,Anna University,2026-01-22T00:00:00.000Z,2026-01-22T10:25:00.079Z,2025-11-27T05:29:05.137Z,Higher Ed/Research,HER Target,null,WWFO;University: India,University,2026-01-22T02:09:48.000Z,annauniv.edu,null,2025-11-27T00:00:00.000Z,Anna University,null
12,9837866,devzone,India,APAC,India,India,SOUTH ASIA,Unacademy,AR / VR;Robotics;Simulation / Modeling / Desig...,null,Academia / Education,null,null,null,null,2025-11-27T07:06:52.000Z,31153,Not Normalized,2025-11-27T07:06:52.000Z,2025-11-27T07:24:59.988Z,2025-11-27T07:06:51.700Z,null,null,null,Manual,NaN,2025-11-26T23:06:52.000Z,null,null,2025-11-27T00:00:00.000Z,Not Normalized,null
13,9839159,dli,India,APAC,India,India,SOUTH ASIA,University of mumbai,Trustworthy AI / Cybersecurity;Simulation / Mo...,null,Financial Services,null,null,null,null,2025-11-27T12:42:05.000Z,8719,University Of Mumbai,2025-11-27T12:42:05.000Z,2025-11-27T12:55:01.303Z,2025-11-27T12:42:04.321Z,null,HER Target,null,University: India;TopUniversities,University,null,mu.ac.in,null,2025-11-27T12:42:05.000Z,University Of Mumbai,null
14,9839522,null,India,APAC,India,India,SOUTH ASIA,null,null,null,Other,null,null,null,null,null,7704,Unclassified - Invalid,2025-11-27T13:33:11.000Z,2025-11-27T13:55:32.249Z,2025-11-27T13:55:32.249Z,null,null,null,null,NaN,null,null,null,2025-11-27T13:33:11.000Z,Unclassified - Invalid,null
15,9839675,dli,India,APAC,India,India,SOUTH ASIA,HCL TECHNOLOGIES,Agentic AI / Generative AI;Computer Vision / V...,null,Other,null,null,null,null,2025-11-27T14:26:49.000Z,2666,HCL Technologies,2025-11-27T14:26:49.000Z,2025-11-27T14:55:01.037Z,2025-11-27T14:26:46.908Z,null,null,null,Company: India;TopOrgs;NV Top 1000 Ent;Forbes ...,Enterprise,2025-11-27T06:35:54.000Z,hcltech.com,null,2025-11-27T14:26:49.000Z,HCL Technologies,null
16,9840887,null,India,APAC,India,India,SOUTH ASIA,null,null,null,Other,null,null,null,null,null,7704,Unclassified - Invalid,2025-11-27T19:00:40.000Z,2025-11-27T19:25:35.616Z,2025-11-27T19:25:35.616Z,null,null,null,null,NaN,null,null,null,2025-11-27T19:00:40.000Z,Unclassified - Invalid,null
17,9844776,dli,India,APAC,India,India,SOUTH ASIA,manakula vinayagar,Agentic AI / Generative AI;Data Science;MLOps;...,null,Other,null,null,null,null,2025-11-28T16:41:58.000Z,31153,Not Normalized,2025-12-08T16:47:05.000Z,2025-12-09T06:08:45.674Z,2025-11-28T16:41:57.341Z,null,null,null,Manual,NaN,null,null,null,2025-11-28T16:41:58.000Z,Not Normalized,null
18,9847157,null,India,APAC,India,India,SOUTH ASIA,STudent,Agentic AI / Generative AI,null,Other,null,null,null,null,null,31153,Not Normalized,null,2025-11-29T11:22:32.896Z,2025-11-29T11:22:32.896Z,null,null,null,Manual,NaN,null,null,null,null,Not Normalized,null
19,9850135,dli,India,APAC,India,India,SOUTH ASIA,T john institute of technology,Trustworthy AI / Cybersecurity;Agentic AI / Ge...,null,Academia / Education,null,null,null,null,2025-11-30T10:31:23.000Z,31153,Not Normalized,2025-11-30T10:31:38.000Z,2025-12-01T02:08:52.355Z,2025-11-30T10:31:22.577Z,null,null,null,Manual,NaN,null,null,null,2025-11-30T10:31:23.000Z,Not Normalized,null
20,9850240,devzone,India,APAC,India,India,SOUTH ASIA,Gujarat technological University,Other,null,Other,null,null,null,null,2025-11-30T11:22:36.000Z,17037,Gujarat Technological University,2025-11-30T11:22:36.000Z,2025-11-30T11:24:57.123Z,2025-11-30T11:22:36.350Z,null,null,null,University: India,University,2025-11-30T03:22:36.000Z,gtu.ac.in,null,2025-11-30T00:00:00.000Z,Gujarat Technological University,null
21,9852754,devzone,India,APAC,India,India,SOUTH ASIA,Lovely Professional University,Content Creation / Rendering;Robotics;Simulati...,null,Gaming,null,null,null,null,2025-12-01T06:46:55.000Z,4558,Lovely Professional University,2025-12-01T11:18:33.000Z,2025-12-05T15:20:47.806Z,2025-12-01T06:46:55.378Z,Higher Ed/Research,HER Target,null,WWFO;University: India,University,2025-11-30T22:46:55.000Z,lpu.in,null,2025-12-01T06:46:55.000Z,Lovely Professional University,null
22,9852847,dli,India,APAC,India,India,SOUTH ASIA,Swami Vivekanand Institute Of Engineering And ...,Trustworthy AI / Cybersecurity;Data Science;Ne...,null,AEC,null,null,null,null,2025-12-01T07:14:41.000Z,31153,Not Normalized,2025-12-01T07:14:41.000Z,2025-12-01T07:24:59.810Z,2025-12-01T07:14:41.005Z,null,null,null,Manual,NaN,null,null,null,2025-12-01T07:14:41.000Z,Not Normalized,null
23,9854248,dli,India,APAC,India,India,SOUTH ASIA,Gayatri vidya Parishad college for degree and ...,Developer Tools & Techniques;Data Science;Agen...,null,AEC,null,null,null,null,2025-12-01T13:22:59.000Z,31153,Not Normalized,2025-12-01T13:23:22.000Z,2025-12-02T01:09:23.040Z,2025-12-01T13:22:57.583Z,null,null,null,Manual,NaN,null,null,null,2025-12-01T13:22:59.000Z,Not Normalized,null
24,985490,gtc,India,APAC,India,India,SOUTH ASIA,PARUL University vadodhara,Trustworthy AI / Cybersecurity;Data Science;co...,null,AEC,null,null,null,null,2024-03-01T07:26:38.000Z,31153,Not Normalized,2024-03-01T07:26:38.000Z,2024-03-01T07:55:07.826Z,2024-03-01T07:26:38.563Z,null,null,null,Manual,NaN,null,null,null,2024-03-01T07:26:38.000Z,Not Normalized,null
25,9857860,dli,India,APAC,India,India,SOUTH ASIA,TEZPUR UNIVERSITY,Trustworthy AI / Cybersecurity;Data Science;Ne...,null,AEC,null,null,null,null,2025-12-02T08:44:34.000Z,2238,Tezpur University,2025-12-02T08:45:30.000Z,2025-12-02T11:08:49.553Z,2025-12-02T08:44:34.248Z,null,null,null,Leadspace;University: India,University,null,tezu.ac.in,null,2025-12-02T08:44:34.000Z,Tezpur University,null
26,9858104,dli,India,APAC,India,India,SOUTH ASIA,Gandhi institute for technological advancements,Trustworthy AI / Cybersecurity;Networking / Co...,null,Telecommunications,null,null,null,null,2025-12-02T09:48:43.000Z,31153,Not Normalized,2025-12-02T09:48:43.000Z,2025-12-02T09:55:01.192Z,2025-12-02T09:48:41.726Z,null,null,null,Manual,NaN,null,null,null,2025-12-02T09:48:43.000Z,Not Normalized,null
27,9858523,dli,India,APAC,India,India,SOUTH ASIA,SRM INSTITUTE OF SCIENCE AND TECHNOLOGY,Agentic AI / Generative AI;Data Science;MLOps;...,null,AEC,null,null,null,null,2025-12-02T11:45:54.000Z,17234,SRM Institute of Science and Technology,2025-12-02T11:46:13.000Z,2025-12-03T01:10:29.898Z,2025-12-02T11:45:53.369Z,null,null,null,University: India,University,null,srmist.edu.in,null,2025-12-02T11:45:54.000Z,SRM Institute of Science and Technology,null
28,9858531,dli,India,APAC,India,India,SOUTH ASIA,GALGOTIAS UNIVERSITY,Content Creation / Rendering;Robotics;Data Cen...,null,Academia / Education,null,null,null,null,2025-12-02T11:48:22.000Z,17027,Galgotias University,2025-12-02T11:48:47.000Z,2025-12-03T01:09:10.967Z,2025-12-02T11:48:21.659Z,null,null,null,University: India,University,null,galgotiasuniversity.edu.in,null,2025-12-02T11:48:22.000Z,Galgotias University,null
29,9859692,dli,India,APAC,India,India,SOUTH ASIA,SRM INSTITUTE OF SCIENCE AND TECHNOLOGY,Data Science;AR / VR;Content Creation / Render...,null,AEC,null,null,null,null,2025-12-02T16:41:56.000Z,17234,SRM Institute of Science and Technology,2025-12-02T16:42:21.000Z,2025-12-03T02:09:50.805Z,2025-12-02T16:41:54.897Z,null,null,null,University: India,University,null,srmist.edu.in,null,2025-12-02T16:41:56.000Z,SRM Institute of Science and Technology,null

In [10]:

con.execute("""
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'contact_raw'
ORDER BY ordinal_position
""").fetchdf()

                        column_name
0                      developer_id
1        program_application_source
2                           country
3                            region
4                        sub_region
5                              zone
6                         territory
7         organization_english_name
8                 development_areas
9           other_development_areas
10        industry_segment_vertical
11  other_industry_segment_vertical
12    sub_industry_segment_vertical
13               fields_of_interest
14         other_fields_of_interest
15   first_program_application_date
16                       account_id
17                     account_name
18               last_activity_date
19               last_modified_date
20                     created_date
21                    wwfo_category
22                 wwfo_target_list
23         account_industry_segment
24                   account_source
25                     account_type
26          devzone_last_login_date
27             organization_website
28                     inception_id
29              first_activity_date
30          normalized_account_name
31                    rdp_exit_date

In [11]:

con.execute("SUMMARIZE contact_clean").fetchdf()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,developer_id,VARCHAR,000006aa196c7510ca3b4617e7e52d9527e0190e9152fb...,fffd473b66da19a680630437ec69aa8c7e450e2cec7848...,9168709,NaN,<NA>,NaN,NaN,NaN,9381490,0.00
1,program_application_source,VARCHAR,GTC,vcalliance,16,NaN,<NA>,NaN,NaN,NaN,9381490,4.76
2,country,VARCHAR,Afghanistan,null,270,NaN,<NA>,NaN,NaN,NaN,9381490,0.03
3,region,VARCHAR,APAC,null,4,NaN,<NA>,NaN,NaN,NaN,9381490,0.03
4,sub_region,VARCHAR,Africa,null,13,NaN,<NA>,NaN,NaN,NaN,9381490,0.03
5,zone,VARCHAR,ANZ,null,21,NaN,<NA>,NaN,NaN,NaN,9381490,0.03
6,territory,VARCHAR,AFRICA,null,18,NaN,<NA>,NaN,NaN,NaN,9381490,3.40
7,organization_english_name,VARCHAR,Babaground,󠀡󠀡,1805457,NaN,<NA>,NaN,NaN,NaN,9381490,0.15
8,development_areas,VARCHAR,AR / VR,null,104551,NaN,<NA>,NaN,NaN,NaN,9381490,0.06
9,other_development_areas,VARCHAR,AI & Digital Solutions;Analytics,？？？,22997,NaN,<NA>,NaN,NaN,NaN,9381490,4.78
10,industry_segment_vertical,VARCHAR,AEC,Telecommunications,23,NaN,<NA>,NaN,NaN,NaN,9381490,0.00
11,other_industry_segment_vertical,VARCHAR,Clinical Medicine,～,43587,NaN,<NA>,NaN,NaN,NaN,9381490,2.67
12,sub_industry_segment_vertical,VARCHAR,Gaming,null,2,NaN,<NA>,NaN,NaN,NaN,9381490,3.89
13,fields_of_interest,VARCHAR,null,null,1,NaN,<NA>,NaN,NaN,NaN,9381490,5.10
14,other_fields_of_interest,VARCHAR,null,null,1,NaN,<NA>,NaN,NaN,NaN,9381490,5.10
15,first_program_application_date,TIMESTAMP,2005-01-01 00:00:00,2026-04-15 10:46:27,6539660,2023-05-05 23:51:20.638831,<NA>,2021-11-29 15:48:49.781682,2023-10-25 17:58:16.773123,2025-03-05 20:13:58.570114,9381490,27.60
16,account_id,VARCHAR,1,9999,33676,NaN,<NA>,NaN,NaN,NaN,9381490,0.00
17,account_name,VARCHAR,#paid,株式会社LINK,35858,NaN,<NA>,NaN,NaN,NaN,9381490,0.00
18,last_activity_date,TIMESTAMP,2002-05-13 04:09:08,2026-04-15 12:46:21,5435375,2023-11-18 14:54:16.308222,<NA>,2022-08-15 04:00:26.066198,2024-05-02 17:00:16.573125,2025-05-11 02:26:48.689358,9381490,17.06
19,last_modified_date,TIMESTAMP,2021-01-30 01:07:18,2026-04-15 12:55:42.962,5075821,2024-11-19 15:13:55.960036,<NA>,2024-05-15 23:46:35.659073,2025-01-06 18:53:01.672494,2025-06-20 05:15:13.08224,9381490,0.00
20,created_date,TIMESTAMP,2013-04-12 17:11:29,2026-03-13 13:30:09.485,7451428,2023-06-08 16:43:51.459924,<NA>,2022-01-01 08:33:58.721522,2023-11-11 21:14:20.512258,2025-02-24 23:23:27.945554,9381490,0.00
21,wwfo_category,VARCHAR,Automotive,null,21,NaN,<NA>,NaN,NaN,NaN,9381490,4.23
22,wwfo_target_list,VARCHAR,Auto_DC_P1,null,91,NaN,<NA>,NaN,NaN,NaN,9381490,4.00
23,account_industry_segment,VARCHAR,null,null,1,NaN,<NA>,NaN,NaN,NaN,9381490,5.10
24,account_source,VARCHAR,Fortune 500: 2021;Forbes Global 2000;Fortune ...,null,425,NaN,<NA>,NaN,NaN,NaN,9381490,1.70
25,account_type,VARCHAR,Enterprise,University,6,NaN,<NA>,NaN,NaN,NaN,9381490,68.26
26,devzone_last_login_date,TIMESTAMP,2011-04-09 13:30:46,2026-04-15 05:54:05,5563482,2023-08-16 11:45:52.195901,<NA>,2022-04-07 21:53:21.572237,2023-11-19 12:11:05.875812,2025-02-18 23:19:58.773908,9381490,47.55
27,organization_website,VARCHAR,-,zzuli.edu.cn,34794,NaN,<NA>,NaN,NaN,NaN,9381490,3.36
28,inception_id,VARCHAR,0011W00001qfUruQAE,null,26569,NaN,<NA>,NaN,NaN,NaN,9381490,4.92
29,first_activity_date,TIMESTAMP,2001-05-30 00:00:00,2026-04-14 13:59:21,4092687,2023-04-27 00:25:17.790083,<NA>,2021-11-06 10:49:48.143944,2023-11-23 02:54:07.35557,2025-03-04 09:20:05.131374,9381490,17.06
30,normalized_account_name,VARCHAR,#paid,株式会社LINK,35858,NaN,<NA>,NaN,NaN,NaN,9381490,0.00
31,rdp_exit_date,TIMESTAMP,2025-04-07 18:49:44,2026-03-11 12:20:10,113,2025-09-18 11:07:20.423423,<NA>,2025-06-27 09:56:44,2025-08-30 03:49:58,2025-12-09 08:26:05.5,9381490,100.00

### SDK Downloads table baseline

In [12]:

con.execute("SELECT COUNT(*) AS row_count FROM sdk_download_clean").fetchdf()

   row_count
0   93038213

In [13]:

con.execute("SELECT * FROM sdk_download_clean LIMIT 30").fetchdf()

,source,sdk_name,product_name,product_release,country,region,subregion,territory,zone,download_date,file_type,operating_system,os_distribution,architecture,kpi,download_count
0,PyPi,NCCL,nvidia-nccl-cu12,2.18.1,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Linux,None,None,1.0,7
1,PyPi,cuRAND,nvidia-curand-cu12,10.3.9.90,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Windows,None,None,1.0,2
2,PyPi,jax_products,jaxlib,0.4.30,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Darwin,None,None,1.0,4
3,PyPi,NVRTC,nvidia-cuda-nvrtc-cu12,12.9.86,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Linux,None,None,1.0,3
4,PyPi,cuRAND,nvidia-curand-cu12,10.3.10.19,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Linux,None,None,1.0,3
5,PyPi,jax_products,jax,0.9.0,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Linux,None,None,1.0,10
6,PyPi,openal_products,triton,2.1.0,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Linux,None,None,1.0,4
7,PyPi,listsonnx_products,onnxruntime,1.17.0,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Linux,None,None,1.0,2
8,PyPi,jax_products,jax,0.8.2,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Darwin,None,None,1.0,1
9,PyPi,tensorflow_products,tensorflow,2.16.1,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Linux,None,None,1.0,5
10,PyPi,lightning_products,lightning,2.3.3,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Darwin,None,None,1.0,1
11,PyPi,optimum_products,optimum,2.1.0,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Windows,None,None,1.0,3
12,PyPi,listsonnx_products,onnxruntime-gpu,1.19.0,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Windows,None,None,1.0,1
13,PyPi,listsonnx_products,onnx,1.20.1,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Linux,None,None,1.0,31
14,PyPi,CUDA Toolkit,nvidia-cuda-runtime-cu12,12.4.127,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Darwin,None,None,1.0,1
15,PyPi,MONAI Core,monai,1.5.2,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Linux,None,None,1.0,15
16,PyPi,cuRAND,nvidia-curand-cu12,10.3.9.90,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Linux,None,None,1.0,429
17,PyPi,jax_products,jax,0.7.0,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Windows,None,None,1.0,1
18,PyPi,jax_products,jax,0.5.1,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Windows,None,None,1.0,1
19,PyPi,jax_products,jax,0.8.3,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Darwin,None,None,1.0,1
20,PyPi,optimum_products,optimum,1.18.0,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Windows,None,None,1.0,2
21,PyPi,listsonnx_products,onnx,1.18.0,MM,APAC,ROAP,NaN,SEA,2026-02-03,Package,Windows,None,None,1.0,1
22,PyPi,Inference Serving,vllm,0.4.2,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Linux,None,None,1.0,1
23,PyPi,jax_products,jax,0.4.35,DZ,EMEA,Africa,AFRICA,Africa,2026-02-03,Package,Darwin,None,None,1.0,1
24,PyPi,tensorflow_products,tensorflow-intel,2.16.1,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Windows,None,None,1.0,1
25,PyPi,listsonnx_products,onnx,1.19.0,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Linux,None,None,1.0,24
26,PyPi,listsonnx_products,onnx,1.14.0,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Windows,None,None,1.0,2
27,PyPi,CUDA Python,cuda-bindings,13.1.1,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Darwin,None,None,1.0,1
28,PyPi,NVRTC,nvidia-cuda-nvrtc-cu12,12.8.93,LT,EMEA,Europe,POLAND_BALTICS,Eastern Europe,2026-02-03,Package,Darwin,None,None,1.0,2
29,PyPi,cuBLAS,nvidia-cublas-cu12,12.4.5.8,MM,APAC,ROAP,NaN,SEA,2026-02-03,Package,Linux,None,None,1.0,9

In [14]:

con.execute("""
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'sdk_download_clean'
ORDER BY ordinal_position
""").fetchdf()

         column_name
0             source
1           sdk_name
2       product_name
3    product_release
4            country
5             region
6          subregion
7          territory
8               zone
9      download_date
10         file_type
11  operating_system
12   os_distribution
13      architecture
14               kpi
15    download_count

In [15]:

con.execute("SUMMARIZE sdk_download_clean").fetchdf()

100% ▕██████████████████████████████████████▏ (00:00:02.60 elapsed)

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,source,VARCHAR,CDN,VSCODE,13,NaN,NaN,NaN,NaN,NaN,93038213,0.00
1,sdk_name,VARCHAR,3DGRUT,tensorflow_products,218,NaN,NaN,NaN,NaN,NaN,93038213,1.37
2,product_name,VARCHAR,(Linux) Acoustic Echo Cancellation,warp-lang,1183,NaN,NaN,NaN,NaN,NaN,93038213,0.00
3,product_release,VARCHAR,0.0,zjyu7g90o5jt/cosmos-1-0-diffusion-7b-text2worl...,11842,NaN,NaN,NaN,NaN,NaN,93038213,1.39
4,country,VARCHAR,AD,ZW,294,NaN,NaN,NaN,NaN,NaN,93038213,1.35
5,region,VARCHAR,APAC,NALA,3,NaN,NaN,NaN,NaN,NaN,93038213,1.35
6,subregion,VARCHAR,Africa,US & Canada,12,NaN,NaN,NaN,NaN,NaN,93038213,1.35
7,territory,VARCHAR,AFRICA,UK_NORDICS,17,NaN,NaN,NaN,NaN,NaN,93038213,42.43
8,zone,VARCHAR,ANZ,Western Europe,20,NaN,NaN,NaN,NaN,NaN,93038213,1.35
9,download_date,DATE,2020-01-01,2026-03-12,2293,2024-05-01 18:07:15.390675,NaN,2023-06-09,2024-10-10,2025-07-25,93038213,0.00
10,file_type,VARCHAR,?,whl,68,NaN,NaN,NaN,NaN,NaN,93038213,1.29
11,operating_system,VARCHAR,AIX,z/OS,230,NaN,NaN,NaN,NaN,NaN,93038213,19.29
12,os_distribution,VARCHAR,1.0,wsl-ubuntu,211,NaN,NaN,NaN,NaN,NaN,93038213,94.56
13,architecture,VARCHAR,ARM,x86_64,15,NaN,NaN,NaN,NaN,NaN,93038213,94.74
14,kpi,DOUBLE,0.0,1.0,2,0.9604637287188103,0.1948670186220706,1.0,1.0,1.0,93038213,1.00
15,download_count,BIGINT,-449443,7589612,85236,164.80492418037738,5023.858590067995,1,2,8,93038213,0.00


## 5. Record counts and uniqueness checks
These checks help identify duplicate inflation, key coverage issues, and whether row counts are aligned with the business meaning of each dataset.

In [16]:

queries = {
    "activity_rows": "SELECT COUNT(*) AS n FROM activity_clean",
    "activity_distinct_devs": "SELECT COUNT(DISTINCT dev_contact) AS n FROM activity_clean",
    "contact_rows": "SELECT COUNT(*) AS n FROM contact_clean",
    "contact_distinct_devs": "SELECT COUNT(DISTINCT developer_id) AS n FROM contact_clean",
    "sdk_rows": "SELECT COUNT(*) AS n FROM sdk_download_clean",
    "sdk_distinct_products": "SELECT COUNT(DISTINCT product_name) AS n FROM sdk_download_clean",
}

{key: con.execute(sql).fetchdf() for key, sql in queries.items()}

{'activity_rows':           n
 0  69347526,
 'activity_distinct_devs':          n
 0  7660278,
 'contact_rows':          n
 0  9381490,
 'contact_distinct_devs':          n
 0  9381490,
 'sdk_rows':           n
 0  93038213,
 'sdk_distinct_products':       n
 0  1158}

## 6. Schema-driven profiling by table

### 6.1 Activity table profiling

In [17]:
con.execute("SELECT activity, COUNT(*) AS cnt FROM activity_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

                                             activity       cnt
0                                   DevZone Downloads  39742594
1                                       NGC Downloads   7720077
2                              Dev Program Membership   6767607
3                                           Model API   6466203
4                                        DLI Training   1934108
5                                     On-Demand Views   1440586
6                                 Conf. Sessions Live   1312509
7                                       User Feedback   1238576
8                                 Forum Contributions    784059
9                              Product Specific Comms    742469
10                                         Conference    401436
11                                           Webinars    320007
12                               Program Applications    219931
13                                               Brev    121821
14                                         Bugs Filed    115133
15                                       Other Events     10502
16                                Event Registrations      7222
17                                           Contests      1440
18                                         Hackathons      1243
19  I want to know how this feature can be manipul...         1
20  during soft link creation in setting up the NV...         1
21              timeout-in-us  = 4096 * (2**timeout)"         1

In [18]:
con.execute("SELECT activity_type, COUNT(*) AS cnt FROM activity_clean GROUP BY 1 ORDER BY cnt DESC LIMIT 50").fetchdf()

                       activity_type       cnt
0                          Installer  36999321
1                           Approved   6654555
2             API Catalog Hosted API   6466203
3                          Container   5345238
4                      Documentation   1791479
5                  Self-Paced Online   1435932
6                       NV On-Demand   1394454
7                 Conference Session   1312509
8                    Feedback Survey   1232012
9                           Resource   1213352
10                            Opt In    742469
11                             Model    671148
12                             Reply    522029
13                    Instructor-Led    498176
14                        Helm Chart    490350
15                        Conference    401436
16                           Samples    292979
17                             Other    261386
18                     Attended Live    193199
19  Registered Developer Application    173571
20                          Firmware    154985
21                             Start    143233
22                            Driver    136776
23                         On Demand    126808
24                    First Response    118794
25                          Software    101176
26                 Workspace Created     89159
27                         Submitted     78646
28                     installer-KPI     54786
29               Program Application     46360
30                             Video     46132
31                 License Agreement     40841
32                 Workspace Started     27349
33                            Denied     18196
34                          Hardware     13885
35                   Needs More Info     11139
36                           Drivers      9192
37                Event Registration      7222
38                     User Feedback      6458
39                              Misc      6116
40                Launchable Created      4678
41                             Draft      3762
42                               Exe      2476
43                           Contest      1440
44                   Installer - KPI      1415
45                         Hackathon      1243
46                          Metadata      1174
47                         Suspended      1132
48                Deployment Created       635
49                            exited       177

In [19]:
con.execute("SELECT activity_attendance, COUNT(*) AS cnt FROM activity_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

                            activity_attendance       cnt
0                                           NaN  56421601
1                                          true   7551663
2                                 Attended Live   1960914
3                      Attended Live;Registered   1699317
4                 Attended On-Demand;Registered   1338780
5                 Registered;Attended On-Demand    156936
6                     Registered; Attended Live    126362
7                      Registered;Attended Live     52684
8   Attended Live;Attended On-Demand;Registered     16653
9                            Attended On-Demand     11986
10  Attended On-Demand;Attended Live;Registered      2164
11  Attended On-Demand;Registered;Attended Live      2032
12  Attended Live;Registered;Attended On-Demand      1920
13  Registered;Attended Live;Attended On-Demand      1864
14  Registered;Attended On-Demand;Attended Live      1706
15             Attended Live;Attended On-Demand       690
16             Attended On-Demand;Attended Live        90
17          Attended Live;Registered;Waitlisted        55
18          Registered;Waitlisted;Attended Live        29
19          Waitlisted;Registered;Attended Live        22
20          Attended Live;Waitlisted;Registered        21
21          Waitlisted;Attended Live;Registered        15
22          Registered;Attended Live;Waitlisted        10
23                     Waitlisted;Attended Live         8
24                                           15         3
25                     Attended Live;Waitlisted         1

In [20]:
con.execute("SELECT activity_role, COUNT(*) AS cnt FROM activity_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

              activity_role       cnt
0                       DZ4  20816265
1                   Devzone  18926329
2                       NaN   9150834
3                       NGC   7720077
4                      NVCF   6466203
5                  Attendee   5247639
6                      User    517729
7                 Moderator    253783
8                 Exhibitor     44318
9                     Other     41124
10             P0-Must have     34964
11            Unprioritized     30625
12           P1-Should have     26697
13        Presenter/Speaker     21750
14                 5-Normal     13338
15            Administrator     12544
16                  Speaker      8953
17          P2-Nice to have      6138
18            *Showstopper*      2704
19          Cost - Employee      1622
20        Financial Analyst      1209
21                    Press      1142
22                  Student       567
23                 1-Urgent       415
24         Industry Analyst       227
25  2-Fix Before Next Build        90
26            0-Showstopper        68
27   3-Fix Before Milestone        46
28          6-Would be Nice        24
29                    Guest        23
30                      VIP        18
31        VivaTech Attendee        16
32        4-Fix Before Ship        15
33                   Vendor        11
34    7-Fix In Next Release         9
35               Researcher         5
36         University Staff         2
37                  5958174         1
38                  6150326         1
39                  4486208         1

In [21]:
con.execute("SELECT activity_score, COUNT(*) AS cnt FROM activity_clean GROUP BY 1 ORDER BY activity_score").fetchdf()

    activity_score       cnt
0              0.0   7304120
1              1.0  10136402
2              2.0    150807
3              3.0  40386220
4              4.0    569597
5              5.0   5173631
6              6.0    635828
7              8.0    143233
8             10.0   1907972
9             15.0     77497
10            20.0   1435932
11            40.0    498176
12           100.0     21750
13        948905.0         1
14        949156.0         1
15        949763.0         1
16             NaN    906358

In [22]:
con.execute("SELECT MIN(activity_date) AS min_date, MAX(activity_date) AS max_date FROM activity_clean").fetchdf()

    min_date            max_date
0 2020-01-01 2026-03-12 17:24:45


### 6.2 Contact table profiling
Use these fields to understand join coverage, organization quality, developer metadata, and potential segmentation dimensions.

In [23]:
con.execute("SELECT country, COUNT(*) AS cnt FROM contact_clean GROUP BY 1 ORDER BY cnt DESC LIMIT 25").fetchdf()

               country      cnt
0        United States  1688338
1                China  1645122
2                India  1111879
3                 null   804111
4   Korea, Republic of   305752
5                Japan   292502
6              Germany   238016
7               Taiwan   213672
8       United Kingdom   209229
9               Canada   159076
10              France   147286
11              Brazil   143200
12  Russian Federation   140301
13           Hong Kong   130632
14           Indonesia    96920
15               Spain    96007
16              Turkey    91227
17           Australia    84460
18            Viet Nam    77264
19              Poland    77022
20               Italy    75084
21           Singapore    75051
22              Israel    72192
23     The Netherlands    61465
24              Mexico    60238

In [24]:
con.execute("SELECT region, COUNT(*) AS cnt FROM contact_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

  region      cnt
0   APAC  4284392
1   NALA  2220135
2   EMEA  2070011
3   null   804111
4    NaN     2841

In [25]:
con.execute("SELECT zone, COUNT(*) AS cnt FROM contact_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

              zone      cnt
0      US & Canada  1847414
1            China  1778896
2            India  1111879
3   Western Europe   974818
4             null   804111
5              SEA   372441
6            LatAm   355049
7      South Korea   305752
8            Japan   292502
9   Eastern Europe   241562
10          Africa   236577
11          Taiwan   213672
12  Rest of Europe   155000
13          Russia   140301
14     Middle East   129206
15          Nordic   120355
16             ANZ    98632
17      South Asia    93434
18          Israel    72192
19      Carribbean    17672
20            ROAP    17184
21             NaN     2841

In [26]:
con.execute("SELECT account_type, COUNT(*) AS cnt FROM contact_clean GROUP BY 1 ORDER BY cnt DESC LIMIT 30").fetchdf()

            account_type      cnt
0                    NaN  6404129
1             University  1980017
2             Enterprise   740459
3                Startup   215987
4  Enterprise;University    16654
5     Startup;University    12856
6     Enterprise;Startup    11388

In [27]:
con.execute("SELECT normalized_account_name, COUNT(*) AS cnt FROM contact_clean GROUP BY 1 ORDER BY cnt DESC LIMIT 30").fetchdf()

                              normalized_account_name      cnt
0                              Unclassified - Invalid  3165684
1                                      Not Normalized  2480837
2                                              NVIDIA    58054
3                               Chandigarh University    34804
4                                   Peking University    29643
5                                 Tsinghua University    26077
6                                 Zhejiang University    21762
7   University of Electronic Science and Technolog...    19395
8                       Shanghai Jiao Tong University    19114
9                              Unclassified - Acronym    18356
10                          Tata Consultancy Services    16159
11                                          Microsoft    15887
12                                           Deloitte    15557
13  Huazhong University of Science and Technology ...    14376
14                                             GOOGLE    14328
15               Karpagam Academy of Higher Education    13942
16                                             Amazon    13852
17                             Wuhan University (WHU)    13722
18                   Savitribai Phule Pune University    13323
19            SRM Institute of Science and Technology    13292
20  Beijing University of Posts and Telecommunicat...    12981
21                                            Infosys    12835
22                                    Anna University    12670
23                                  Dell Technologies    11930
24  University of Science and Technology of China ...    11764
25                               University Of Mumbai    11378
26                VIT Vellore Institute of Technology    11174
27                            Northeastern University    11124
28                                Samsung Electronics    10647
29                                   Parul University    10514

In [28]:
con.execute("SELECT program_application_source, COUNT(*) AS cnt FROM contact_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

   program_application_source      cnt
0                        null  4006295
1                     devzone  2806574
2                         dli  1004037
3                         gtc   448297
4                         NaN   446092
5                 api_catalog   391786
6               GTC Fall 2022   107396
7             GTC Spring 2022    89807
8                         nod    46301
9                        brev    10869
10                  inception     9213
11                        ngc     6251
12                   aisummit     5367
13                        hwg     2294
14                        GTC      594
15                 vcalliance      164
16                    connect      136
17                  aem_event       17

In [29]:
con.execute("SELECT MIN(first_activity_date) AS first_seen, MAX(last_activity_date) AS last_seen FROM contact_clean").fetchdf()

  first_seen           last_seen
0 2001-05-30 2026-04-15 12:46:21


### 6.3 SDK download profiling
This section profiles technology adoption behavior by source, product, operating system, and geography.

In [30]:
con.execute("SELECT source, COUNT(*) AS cnt FROM sdk_download_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

             source       cnt
0              PyPi  71366571
1               CDN  16256643
2               NGC   4180625
3        CDN - PyPI    774093
4            GitHub    175664
5         CDN - APT     68791
6   CDN - Workbench     55483
7             Conda     47921
8       CDN - Azure     39300
9         DOCKERHUB     38529
10      Huggingface     25101
11        CDN - GCP      6901
12           VSCODE      1643
13             Rust       948

In [31]:
con.execute("SELECT sdk_name, COUNT(*) AS cnt FROM sdk_download_clean GROUP BY 1 ORDER BY cnt DESC LIMIT 50").fetchdf()

                sdk_name       cnt
0    tensorflow_products  12104248
1     listsonnx_products   7631106
2           CUDA Toolkit   7350940
3           jax_products   7045281
4     lightning_products   7006933
5       pytorch_products   5729419
6                  cuDNN   3546075
7                 Triton   2553631
8      Inference Serving   2323808
9                   NCCL   2297304
10              TensorRT   2244818
11         cupy_products   2151023
12         Deep Learning   1766499
13      optimum_products   1763843
14  onnx_bridge_products   1751584
15              cuSPARSE   1582046
16                cuBLAS   1385762
17                   NaN   1272427
18                Jetson   1250932
19                 NVRTC   1226666
20         msft_products   1211602
21       openal_products   1179551
22                 CUPTI   1167000
23                cuRAND   1128035
24              cuSOLVER   1121263
25                 cuFFT   1108726
26        intel_products   1026485
27                  NVTX    973632
28              cuTENSOR    802179
29        NeMo Framework    752586
30       mosaic_products    508513
31                Nsight    464509
32                  DALI    463144
33            MONAI Core    421143
34         Texture Tools    414509
35                RAPIDS    338452
36            DeepStream    300746
37             cuQuantum    267588
38      Kernel Authoring    264027
39               HPC SDK    232412
40         Megatron Core    202874
41                cuFile    201743
42           RAPIDS/cuml    198473
43            flashInfer    182412
44                  Warp    155837
45           CUDA Python    146679
46               NVSHMEM    128999
47                 Optix    126433
48            RAPIDS/rmm    125390
49            nvJPEG2000    124891

In [32]:
con.execute("SELECT product_name, COUNT(*) AS cnt FROM sdk_download_clean GROUP BY 1 ORDER BY cnt DESC LIMIT 50").fetchdf()

                   product_name      cnt
0                    tensorflow  9207348
1             pytorch-lightning  5702569
2                         torch  5607273
3                  CUDA Toolkit  5404957
4                           jax  4926955
5                   onnxruntime  2905723
6                          onnx  2543826
7                         cuDNN  2108422
8                        jaxlib  2070727
9                          vllm  1710983
10                     TensorRT  1451692
11               tensorflow-cpu  1375765
12                      optimum  1315137
13          nvidia/tritonserver  1300911
14              onnxruntime-gpu  1292155
15                    lightning  1275181
16                         cupy  1212566
17                    deepspeed  1211602
18                 tritonclient  1182165
19                       triton  1133052
20             tensorflow-intel  1102357
21               nvidia/pytorch  1076193
22             nvidia-nccl-cu12  1015190
23                         NCCL  1002554
24           nvidia-cublas-cu12  1000698
25     nvidia-cuda-runtime-cu12   978620
26            nvidia-cudnn-cu12   969238
27         nvidia-cusparse-cu12   938821
28       nvidia-cuda-nvrtc-cu12   936717
29       nvidia-cuda-cupti-cu12   923250
30            nvidia-cufft-cu12   914229
31           nvidia-curand-cu12   901980
32         nvidia-cusolver-cu12   872610
33                  JetPack SDK   843321
34              onnx-simplifier   767251
35                     cuTENSOR   748821
36                      tf2onnx   684590
37             nvidia-nvtx-cu12   675580
38                       sglang   612825
39            nvidia/tensorflow   599175
40                     openvino   594282
41            CUDA Toolkit-repo   585087
42                      onnx2tf   584223
43                 nemo-toolkit   551911
44            nvidia-cudnn-cu11   467447
45                     tensorrt   437948
46              tensorflow-rocm   418778
47                        monai   417623
48                  JetPack L4T   363117
49  Texture Tools for PhotoShop   339864

In [33]:
con.execute("SELECT file_type, COUNT(*) AS cnt FROM sdk_download_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

               file_type       cnt
0                Package  71442184
1        Installer - KPI   9508317
2              Container   4180223
3              Installer   1842700
4          Documentation   1287318
5                    NaN   1199133
6                    whl   1089181
7          Installer-KPI    909504
8                  Image    235093
9          Installer KPI    215591
10         installer-KPI    199676
11            Repository    175664
12                 video    158774
13               Samples    119025
14  Installer - KPI-repo     81346
15                 Wheel     68987
16                  Misc     61514
17             installer     34263
18                 Video     34153
19          MODEL_SCRIPT     32234
20                   rpm     25039
21                   Doc     20924
22                   deb     19273
23               Drivers     15332
24         Installer deb     14529
25     License Agreement      7709
26            HELM_CHART      6782
27                Videos      6526
28                Driver      5919
29         Installer rpm      5500
30                Binary      4421
31                 image      4395
32                Header      2857
33                Update      1969
34                   bfb      1830
35                 Other      1777
36           Source Code      1765
37                   CPP      1712
38              Checksum      1692
39                 MODEL      1365
40         Installer pdf      1361
41                Sample      1151
42         Installer run      1032
43                  Data       979
44              Metadata       962
45         Installer whl       788
46              Document       753
47               License       753
48         Installer msi       704
49            User Guide       638
50    Installation Guide       599
51         Installer dmg       477
52          Product Deck       410
53               Roadmap       376
54         Release Notes       322
55         Installer tar       279
56           tar archive       190
57                  NULL       123
58                   iso        59
59            COLLECTION        43
60                  MIsc        15
61                     ?         1
62                Poster         1
63         documentation         1

In [34]:
con.execute("SELECT operating_system, COUNT(*) AS cnt FROM sdk_download_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

             operating_system       cnt
0                       Linux  37102242
1                     Windows  24154098
2                         NaN  17946361
3                      Darwin   8695657
4                   Linux x86   2947007
..                        ...       ...
209                       Nto         1
210     MINGW32_NT-10.0-19043         1
211       MINGW64_NT-10.0-WOW         1
212  CYGWIN_NT-6.3-9600-WOW64         1
213                         L         1

[214 rows x 2 columns]

In [35]:
con.execute("SELECT architecture, COUNT(*) AS cnt FROM sdk_download_clean GROUP BY 1 ORDER BY cnt DESC").fetchdf()

      architecture       cnt
0              NaN  88142755
1           x86_64   3979916
2              ARM    506941
3          aarch64    149427
4       arm64-sbsa     67088
5          PowerPC     60500
6              x86     35593
7            Amd64     34124
8   aarch64-jetson     30890
9        Universal     10735
10           Arm64      9645
11            sbsa      5588
12           POWER      2912
13             PPC      2099

In [36]:
con.execute("SELECT MIN(download_date) AS first_download, MAX(download_date) AS last_download FROM sdk_download_clean").fetchdf()

  first_download last_download
0     2020-01-01    2026-03-12


## 7. Data quality checks
Before drawing conclusions, quantify nulls, duplicates, invalid values, and join failures.

In [37]:

quality_queries = {
    "activity_nulls": """
        SELECT
            COUNT(*) AS total_rows,
            SUM(CASE WHEN dev_contact IS NULL THEN 1 ELSE 0 END) AS null_dev_contact,
            SUM(CASE WHEN activity_date IS NULL THEN 1 ELSE 0 END) AS null_activity_date,
            SUM(CASE WHEN activity IS NULL THEN 1 ELSE 0 END) AS null_activity,
            SUM(CASE WHEN activity_score IS NULL THEN 1 ELSE 0 END) AS null_activity_score,
            SUM(CASE WHEN activity_id IS NULL THEN 1 ELSE 0 END) AS null_activity_id
        FROM activity_clean
    """,
    "contact_nulls": """
        SELECT
            COUNT(*) AS total_rows,
            SUM(CASE WHEN developer_id IS NULL THEN 1 ELSE 0 END) AS null_developer_id,
            SUM(CASE WHEN country IS NULL THEN 1 ELSE 0 END) AS null_country,
            SUM(CASE WHEN region IS NULL THEN 1 ELSE 0 END) AS null_region,
            SUM(CASE WHEN normalized_account_name IS NULL THEN 1 ELSE 0 END) AS null_normalized_account_name,
            SUM(CASE WHEN first_activity_date IS NULL THEN 1 ELSE 0 END) AS null_first_activity_date
        FROM contact_clean
    """,
    "sdk_nulls": """
        SELECT
            COUNT(*) AS total_rows,
            SUM(CASE WHEN source IS NULL THEN 1 ELSE 0 END) AS null_source,
            SUM(CASE WHEN product_name IS NULL THEN 1 ELSE 0 END) AS null_productname,
            SUM(CASE WHEN download_date IS NULL THEN 1 ELSE 0 END) AS null_downloaddate,
            SUM(CASE WHEN country IS NULL THEN 1 ELSE 0 END) AS null_country
        FROM sdk_download_clean
    """
}

{key: con.execute(sql).fetchdf() for key, sql in quality_queries.items()}

{'activity_nulls':    total_rows  null_dev_contact  null_activity_date  null_activity  \
 0    69347526              25.0                 3.0            0.0

    null_activity_score  null_activity_id
 0             906358.0              20.0  ,
 'contact_nulls':    total_rows  null_developer_id  null_country  null_region  \
 0     9381490                0.0        2841.0       2841.0

    null_normalized_account_name  null_first_activity_date
 0                           0.0                 1600085.0  ,
 'sdk_nulls':    total_rows  null_source  null_productname  null_downloaddate  null_country
 0    93038213          0.0               0.0                0.0     1254777.0}

In [38]:

con.execute("""
SELECT activity_id, COUNT(*) AS cnt
FROM activity_clean
WHERE activity_id IS NOT NULL
GROUP BY 1
HAVING COUNT(*) > 1
ORDER BY cnt DESC
LIMIT 50
""").fetchdf()

100% ▕██████████████████████████████████████▏ (00:00:02.10 elapsed)

           activity_id  cnt
0   SURVEY_185-6182646  398
1   SURVEY_185-6475434  172
2   SURVEY_185-6228214  159
3    hzqaa2mdg-8519393  146
4    SURVEY_185-539824  137
5   SURVEY_185-4790429  118
6   SURVEY_185-2544411  115
7    r5qmxaqcv-3199690  105
8   SURVEY_185-6522069   81
9    v16whbpr2-9091179   80
10  SURVEY_185-6385506   78
11  SURVEY_185-2539142   76
12  t9eixpx24-10003170   73
13  SURVEY_185-6419185   72
14   SURVEY_185-147118   71
15   r9rinoo4y-6688696   64
16   8fp8ljrd5-9991671   62
17  SURVEY_185-1413068   61
18  SURVEY_185-7182300   58
19  SURVEY_185-6423459   58
20   pb2sveceg-9983737   58
21   kkoreil7q-7115221   55
22  c1s0hjwpl-10003180   54
23   iv0hp4y6k-9987354   53
24  SURVEY_185-3696893   53
25   dtef0m4ta-9989156   53
26   twsq0nmln-9987354   51
27    SURVEY_185-37202   51
28   kd9wo4awf-8488534   50
29   178fm8y2g-4930318   48
30   vbz6haoqz-9988663   47
31   6tj9k0aqt-9496752   47
32   2hg3cmnrc-3891540   47
33   2ji25o86j-9506604   46
34   nyj4wtblk-6438194   45
35   ihibotsup-9080381   45
36   rxxbgppei-9296101   45
37  SURVEY_185-2910800   44
38   ptdcp4g30-5865378   43
39  SURVEY_185-6112856   43
40   q6ly46kpx-9296101   42
41   SURVEY_185-780915   41
42   k6r0zky0h-9984391   41
43  SURVEY_185-5098107   39
44   igo7ka45g-9296101   39
45    92g2jxu5-6301510   39
46  SURVEY_185-6583131   38
47  69chjp1sa-10003271   38
48   655p0iixg-9988085   38
49   y87g7wnyp-9528404   36

In [39]:

con.execute("""
SELECT pk1, COUNT(*) AS cnt
FROM activity_clean
WHERE pk1 IS NOT NULL
GROUP BY 1
HAVING COUNT(*) > 1
ORDER BY cnt DESC
LIMIT 50
""").fetchdf()

                   pk1  cnt
0   SURVEY_185-6182646  398
1   SURVEY_185-6475434  172
2   SURVEY_185-6228214  159
3    hzqaa2mdg-8519393  146
4    SURVEY_185-539824  137
5   SURVEY_185-4790429  118
6   SURVEY_185-2544411  115
7    r5qmxaqcv-3199690  105
8   SURVEY_185-6522069   81
9    v16whbpr2-9091179   80
10  SURVEY_185-6385506   78
11  SURVEY_185-2539142   76
12  t9eixpx24-10003170   73
13  SURVEY_185-6419185   72
14   SURVEY_185-147118   71
15   r9rinoo4y-6688696   64
16   8fp8ljrd5-9991671   62
17  SURVEY_185-1413068   61
18  SURVEY_185-7182300   58
19   pb2sveceg-9983737   58
20  SURVEY_185-6423459   58
21   kkoreil7q-7115221   55
22  c1s0hjwpl-10003180   54
23  SURVEY_185-3696893   53
24   iv0hp4y6k-9987354   53
25   dtef0m4ta-9989156   53
26    SURVEY_185-37202   51
27   twsq0nmln-9987354   51
28   kd9wo4awf-8488534   50
29   178fm8y2g-4930318   48
30   vbz6haoqz-9988663   47
31   6tj9k0aqt-9496752   47
32   2hg3cmnrc-3891540   47
33   2ji25o86j-9506604   46
34   ihibotsup-9080381   45
35   rxxbgppei-9296101   45
36   nyj4wtblk-6438194   45
37  SURVEY_185-2910800   44
38   ptdcp4g30-5865378   43
39  SURVEY_185-6112856   43
40   q6ly46kpx-9296101   42
41   k6r0zky0h-9984391   41
42   SURVEY_185-780915   41
43  SURVEY_185-5098107   39
44   igo7ka45g-9296101   39
45    92g2jxu5-6301510   39
46  69chjp1sa-10003271   38
47  SURVEY_185-6583131   38
48   655p0iixg-9988085   38
49   y87g7wnyp-9528404   36

In [40]:

con.execute("""
SELECT developer_id, COUNT(*) AS cnt
FROM contact_clean
GROUP BY 1
HAVING COUNT(*) > 1
ORDER BY cnt DESC
LIMIT 50
""").fetchdf()

Empty DataFrame
Columns: [developer_id, cnt]
Index: []

In [41]:

con.execute("""
SELECT country, COUNT(DISTINCT region) AS region_count
FROM contact_clean
WHERE country IS NOT NULL
GROUP BY 1
HAVING COUNT(DISTINCT region) > 1
ORDER BY region_count DESC, country
""").fetchdf()

Empty DataFrame
Columns: [country, region_count]
Index: []


## 8. Join coverage and entity alignment
This section determines how well the three tables connect at the developer level and where the data model has blind spots.

In [42]:

con.execute("""
SELECT
    COUNT(DISTINCT a.dev_contact) AS activity_developers,
    COUNT(DISTINCT c.developer_id) AS contact_developers,
    COUNT(DISTINCT a.dev_contact) FILTER (WHERE c.developer_id IS NOT NULL) AS activity_devs_found_in_contacts,
    COUNT(DISTINCT a.dev_contact) FILTER (WHERE c.developer_id IS NULL) AS activity_devs_missing_in_contacts
FROM activity_clean a
LEFT JOIN contact_clean c
    ON a.dev_contact = c.developer_id
""").fetchdf()

100% ▕██████████████████████████████████████▏ (00:00:02.08 elapsed)

,activity_developers,contact_developers,activity_devs_found_in_contacts,activity_devs_missing_in_contacts
0,7660278,7660260,7660260,18


If the SDK table does not contain a developer identifier, treat it as product and geography level adoption evidence rather than person-level adoption. If it does contain one in your local version, replace the placeholder column name below and run the join coverage test.

In [43]:

# Replace sdk_dev_key with the correct developer join field if one exists in your local sdk_download_clean table.
# Example: sdk_dev_key = "developer_id"
sdk_dev_key = None

if sdk_dev_key:
    query = f"""
    SELECT
        COUNT(DISTINCT {sdk_dev_key}) AS sdk_developers,
        COUNT(DISTINCT {sdk_dev_key}) FILTER (WHERE c.developer_id IS NOT NULL) AS sdk_devs_found_in_contacts,
        COUNT(DISTINCT {sdk_dev_key}) FILTER (WHERE c.developer_id IS NULL) AS sdk_devs_missing_in_contacts
    FROM sdk_download_clean s
    LEFT JOIN contact_clean c
        ON s.{sdk_dev_key} = c.developer_id
    """
    display(con.execute(query).fetchdf())
else:
    print("No developer-level join field configured for sdk_download_clean.")

No developer-level join field configured for sdk_download_clean.


## 9. Temporal consistency and developer journey checks
These checks look for timeline contradictions and early signs of journey funnel structure.

In [44]:

con.execute("""
SELECT COUNT(*) AS activities_before_first_activity
FROM activity_clean a
JOIN contact_clean c
    ON a.dev_contact = c.developer_id
WHERE a.activity_date < CAST(c.first_activity_date AS DATE)
""").fetchdf()

   activities_before_first_activity
0                                36

In [45]:

con.execute("""
SELECT COUNT(*) AS activities_after_last_activity
FROM activity_clean a
JOIN contact_clean c
    ON a.dev_contact = c.developer_id
WHERE c.last_activity_date IS NOT NULL
  AND a.activity_date > CAST(c.last_activity_date AS DATE)
""").fetchdf()

   activities_after_last_activity
0                         6527407

In [46]:

con.execute("""
SELECT
    DATE_TRUNC('month', activity_date) AS month,
    COUNT(*) AS activity_rows,
    COUNT(DISTINCT dev_contact) AS active_developers
FROM activity_clean
GROUP BY 1
ORDER BY 1
""").fetchdf()

        month  activity_rows  active_developers
0  2020-01-01         583859              86164
1  2020-02-01         562155              87388
2  2020-03-01         642292             106830
3  2020-04-01         679316             119127
4  2020-05-01         722268             119708
5  2020-06-01         729770             114933
6  2020-07-01         774524             111654
7  2020-08-01         651875             103609
8  2020-09-01         699645             115548
9  2020-10-01         913007             137373
10 2020-11-01         834591             122642
11 2020-12-01         729708             117180
12 2021-01-01         711900             118514
13 2021-02-01         623301             104500
14 2021-03-01         819315             138078
15 2021-04-01        1422841             275668
16 2021-05-01         674986             126928
17 2021-06-01         648965             118223
18 2021-07-01         625038             116254
19 2021-08-01         683517             104938
20 2021-09-01         680589             106661
21 2021-10-01         675542             108214
22 2021-11-01         808878             137724
23 2021-12-01         642876             111763
24 2022-01-01         628104             116799
25 2022-02-01         592429             121749
26 2022-03-01        1117290             235727
27 2022-04-01         791776             130987
28 2022-05-01         776522             119672
29 2022-06-01         743837             115435
30 2022-07-01         730863             115128
31 2022-08-01         799757             147098
32 2022-09-01        1047664             222504
33 2022-10-01         755720             123213
34 2022-11-01         795477             131831
35 2022-12-01         649711             114072
36 2023-01-01         668254             131067
37 2023-02-01         735458             152471
38 2023-03-01        1330101             315227
39 2023-04-01         876042             167942
40 2023-05-01         810215             152222
41 2023-06-01         740105             146016
42 2023-07-01         719059             139911
43 2023-08-01         727163             137332
44 2023-09-01         685982             142953
45 2023-10-01         730816             148594
46 2023-11-01         733082             167930
47 2023-12-01         667552             142446
48 2024-01-01         759262             157394
49 2024-02-01         705966             164551
50 2024-03-01        1421772             330940
51 2024-04-01         915417             183863
52 2024-05-01         880465             165220
53 2024-06-01         845499             175683
54 2024-07-01         957879             177997
55 2024-08-01         896989             181815
56 2024-09-01         873178             187950
57 2024-10-01        1021174             222322
58 2024-11-01         961444             198531
59 2024-12-01         972558             209715
60 2025-01-01        1157712             284221
61 2025-02-01        1292046             297716
62 2025-03-01        1872375             361356
63 2025-04-01        1242227             241312
64 2025-05-01        1198154             231230
65 2025-06-01        1169780             215381
66 2025-07-01        1403115             249270
67 2025-08-01        1295592             204982
68 2025-09-01        1201573             189432
69 2025-10-01        1262909             204719
70 2025-11-01        1320180             191150
71 2025-12-01        1411284             186617
72 2026-01-01        1950267             241894
73 2026-02-01        2461752             336446
74 2026-03-01        1503217             228863
75        NaT              3                  0


## 10. Activity intensity and developer-level aggregation
A developer-level feature table is the bridge between exploratory analysis and segmentation.

In [47]:

developer_features_query = """
WITH activity_features AS (
    SELECT
        dev_contact AS developer_id,
        COUNT(*) AS activity_rows,
        COUNT(DISTINCT activity) AS distinct_activity_categories,
        COUNT(DISTINCT activity_name) AS distinct_activity_names,
        SUM(COALESCE(activity_score, 0)) AS total_activity_score,
        AVG(COALESCE(activity_score, 0)) AS avg_activity_score,
        MIN(activity_date) AS first_activity_date_from_events,
        MAX(activity_date) AS last_activity_date_from_events,
        COUNT(*) FILTER (WHERE activity = 'Webinars') AS webinar_rows,
        COUNT(*) FILTER (WHERE activity = 'DLI Training') AS dli_rows,
        COUNT(*) FILTER (WHERE activity = 'Hackathon') AS hackathon_rows,
        COUNT(*) FILTER (WHERE activity = 'Forum Contributions') AS forum_rows,
        COUNT(*) FILTER (WHERE activity = 'Hosted API') AS hosted_api_rows,
        COUNT(*) FILTER (WHERE activity = 'DevZone Downloads') AS devzone_download_rows,
        COUNT(*) FILTER (WHERE activity = 'NGC Downloads') AS ngc_download_rows
    FROM activity_clean
    GROUP BY 1
)
SELECT
    af.*, 
    c.country,
    c.region,
    c.zone,
    c.account_type,
    c.program_application_source,
    c.normalized_account_name,
    c.first_activity_date,
    c.last_activity_date
FROM activity_features af
LEFT JOIN contact_clean c
    ON af.developer_id = c.developer_id
"""

dev_features = con.execute(developer_features_query).fetchdf()
dev_features.head()

100% ▕██████████████████████████████████████▏ (00:00:16.16 elapsed)
 73% ▕███████████████████████████▋          ▏ (~28 seconds remaining)

,developer_id,activity_rows,distinct_activity_categories,distinct_activity_names,total_activity_score,avg_activity_score,first_activity_date_from_events,last_activity_date_from_events,webinar_rows,dli_rows,hackathon_rows,forum_rows,hosted_api_rows,devzone_download_rows,ngc_download_rows,country,region,zone,account_type,program_application_source,normalized_account_name,first_activity_date,last_activity_date
0,889124,4,4,4,27.0,6.750000,2022-05-25 00:00:00,2025-11-19 08:37:48,0,1,0,0,0,1,0,Israel,EMEA,Israel,NaN,null,Arbe Robotics,2018-08-13 00:00:00,2025-11-19 08:37:48
1,3184433,34,4,5,172.0,5.058824,2023-01-18 01:45:33,2026-01-19 00:00:00,0,2,0,0,0,29,0,Taiwan,APAC,Taiwan,NaN,dli,Not Normalized,2023-01-18 01:45:33,2026-01-19 00:00:00
2,6112715,8,1,4,320.0,40.000000,2022-04-07 05:49:05,2022-04-28 05:41:24,0,8,0,0,0,0,0,China,APAC,China,Enterprise,null,LY Corporation,2022-04-07 05:49:05,2022-04-28 05:41:24
3,5887378,73,7,55,1008.0,13.808219,2020-07-12 00:00:00,2026-01-22 07:49:57,4,28,0,0,0,14,0,Singapore,APAC,SEA,Enterprise,NaN,Edwards Lifesciences,2014-12-30 00:00:00,2026-01-22 07:49:57
4,9371020,3,2,3,41.0,13.666667,2025-08-13 04:35:30,2025-08-13 04:38:11,0,2,0,0,0,0,0,India,APAC,India,University,dli,Symbiosis International University,2025-08-13 04:35:30,2025-08-13 04:38:11

In [48]:
dev_features.describe(include="all").transpose()

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
developer_id,7660278,7660278,889124,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
activity_rows,7660279.0,NaN,NaN,NaN,9.052872,1.0,1.0,2.0,4.0,2027375.0,800.05119
distinct_activity_categories,7660279.0,NaN,NaN,NaN,1.951847,1.0,1.0,2.0,2.0,16.0,0.878217
distinct_activity_names,7660279.0,NaN,NaN,NaN,2.809851,0.0,1.0,2.0,3.0,10748.0,11.012568
total_activity_score,7660279.0,NaN,NaN,NaN,31.149613,0.0,3.0,7.0,20.0,10015132.0,4064.747477
avg_activity_score,7660279.0,NaN,NaN,NaN,3.963967,0.0,1.75,2.333333,3.0,113915.24,41.44732
first_activity_date_from_events,7660279,NaN,NaN,NaN,2023-08-11 17:49:48.343630,2020-01-01 00:00:00,2022-02-18 00:00:00,2024-01-04 00:00:00,2025-03-10 10:56:43,2026-03-12 17:24:45,NaN
last_activity_date_from_events,7660279,NaN,NaN,NaN,2023-12-16 22:31:47.008409,2020-01-01 00:00:00,2022-09-13 11:36:43,2024-05-15 08:46:05,2025-05-13 05:35:40.500000,2026-03-12 17:24:45,NaN
webinar_rows,7660279.0,NaN,NaN,NaN,0.041775,0.0,0.0,0.0,0.0,132.0,0.402579
dli_rows,7660279.0,NaN,NaN,NaN,0.252485,0.0,0.0,0.0,0.0,228.0,1.048795
hackathon_rows,7660279.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
forum_rows,7660279.0,NaN,NaN,NaN,0.102354,0.0,0.0,0.0,0.0,36747.0,21.776846
hosted_api_rows,7660279.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
devzone_download_rows,7660279.0,NaN,NaN,NaN,5.188139,0.0,0.0,1.0,2.0,151937.0,68.475957
ngc_download_rows,7660279.0,NaN,NaN,NaN,1.007806,0.0,0.0,0.0,0.0,2027374.0,796.186574
country,7657486,250,China,1481292,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,7657486,4,APAC,3738835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zone,7657486,21,US & Canada,1612903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_type,2696795,6,University,1856998,NaN,NaN,NaN,NaN,NaN,NaN,NaN
program_application_source,7215783,17,null,2748933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
normalized_account_name,7660260,36728,Not Normalized,2156260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
first_activity_date,7660260,NaN,NaN,NaN,2023-05-24 01:00:57.838544,2001-05-30 00:00:00,2021-12-15 00:00:00,2023-12-11 20:46:35,2025-03-07 00:18:52.500000,2026-03-12 17:22:02,NaN
last_activity_date,7660260,NaN,NaN,NaN,2023-12-17 13:29:47.532516,2020-01-01 00:00:00,2022-09-13 17:32:48.500000,2024-05-16 00:00:00,2025-05-13 18:31:42.250000,2026-04-15 12:27:17,NaN


## 11. Investigating weird patterns and anomalies
This section directly targets unusual behavior that may become high-value business insights.

In [49]:

con.execute("""
SELECT activity, AVG(COALESCE(activity_score, 0)) AS avg_score, MIN(activity_score) AS min_score, MAX(activity_score) AS max_score
FROM activity_clean
GROUP BY 1
ORDER BY avg_score DESC
""").fetchdf()

,activity,avg_score,min_score,max_score
0,I want to know how this feature can be manipul...,949763.000000,949763.0,949763.0
1,"timeout-in-us = 4096 * (2**timeout)""",949156.000000,949156.0,949156.0
2,during soft link creation in setting up the NV...,948905.000000,948905.0,948905.0
3,DLI Training,25.151481,20.0,40.0
4,Conf. Sessions Live,10.804406,10.0,100.0
5,Conference,9.985589,3.0,100.0
6,Webinars,7.099192,0.0,10.0
7,Other Events,5.737479,3.0,10.0
8,NGC Downloads,4.247388,1.0,6.0
9,On-Demand Views,3.713054,0.0,100.0
10,Forum Contributions,3.399697,0.0,15.0
11,Product Specific Comms,3.000000,3.0,3.0
12,Event Registrations,3.000000,3.0,3.0
13,Hackathons,3.000000,3.0,3.0
14,Contests,3.000000,3.0,3.0
15,User Feedback,2.937242,3.0,3.0
16,DevZone Downloads,2.851110,0.0,5.0
17,Dev Program Membership,0.971364,0.0,1.0
18,Program Applications,0.070809,0.0,3.0
19,Model API,0.000000,0.0,0.0
20,Brev,0.000000,NaN,NaN
21,Bugs Filed,0.000000,NaN,NaN

In [50]:

con.execute("""
SELECT dev_contact, COUNT(*) AS rows_per_dev, SUM(COALESCE(activity_score, 0)) AS total_score
FROM activity_clean
GROUP BY 1
ORDER BY total_score DESC, rows_per_dev DESC
LIMIT 50
""").fetchdf()

   dev_contact  rows_per_dev  total_score
0      5903679       2027375   10015132.0
1      5886356        789400    3946993.0
2          NaN            25    2847881.0
3      3931685        187095     934975.0
4      2028858        142980     714100.0
5      1303597        151947     449262.0
6      6125204         68992     344958.0
7      4833930         55061     275414.0
8       225774         53677     267525.0
9      6309430        121950     233315.0
10     5671110         49514     198000.0
11     4634152        107089     180735.0
12     6002581         33768     159237.0
13     5455362         28335     152270.0
14     3135781         34322     149354.0
15     7356313         29616     148076.0
16     6502867         38320     121596.0
17     6112577         30443     116628.0
18     4800966         20380     115352.0
19     5944779         18907     110049.0
20     6002252         18076     105282.0
21     5983317         33141      98743.0
22     6149082         16674      97918.0
23     8124370           971      97010.0
24     4595041         29948      91838.0
25     6056403         17967      87847.0
26     5859033         37067      85365.0
27     6522695         12479      82887.0
28     6590114         20171      79401.0
29      186649         15852      79260.0
30     5913714         33056      78958.0
31     8814735         15646      78226.0
32     7473806         13516      77655.0
33     6335105         15126      75611.0
34     3943832         27574      74065.0
35     6606343         19514      73720.0
36      189874         15337      73545.0
37     4458058         15248      73138.0
38     1308818         23477      70124.0
39     4491945         15415      67790.0
40      220689         14180      66918.0
41     4093853         11263      66369.0
42      261299         13041      64900.0
43     5944795         15933      64831.0
44     6617399         15663      64823.0
45     6135512         38937      64594.0
46     6617049         15596      64268.0
47         783          6277      62691.0
48     5964425         12471      60138.0
49     6194236         11980      60048.0

In [51]:

con.execute("""
SELECT normalized_account_name, COUNT(*) AS dev_count
FROM contact_clean
WHERE normalized_account_name IS NOT NULL
GROUP BY 1
ORDER BY dev_count DESC
LIMIT 50
""").fetchdf()

                              normalized_account_name  dev_count
0                              Unclassified - Invalid    3165684
1                                      Not Normalized    2480837
2                                              NVIDIA      58054
3                               Chandigarh University      34804
4                                   Peking University      29643
5                                 Tsinghua University      26077
6                                 Zhejiang University      21762
7   University of Electronic Science and Technolog...      19395
8                       Shanghai Jiao Tong University      19114
9                              Unclassified - Acronym      18356
10                          Tata Consultancy Services      16159
11                                          Microsoft      15887
12                                           Deloitte      15557
13  Huazhong University of Science and Technology ...      14376
14                                             GOOGLE      14328
15               Karpagam Academy of Higher Education      13942
16                                             Amazon      13852
17                             Wuhan University (WHU)      13722
18                   Savitribai Phule Pune University      13323
19            SRM Institute of Science and Technology      13292
20  Beijing University of Posts and Telecommunicat...      12981
21                                            Infosys      12835
22                                    Anna University      12670
23                                  Dell Technologies      11930
24  University of Science and Technology of China ...      11764
25                               University Of Mumbai      11378
26                VIT Vellore Institute of Technology      11174
27                            Northeastern University      11124
28                                Samsung Electronics      10647
29                                   Parul University      10514
30                                          Accenture      10197
31                     Harbin Institute of Technology      10184
32              Visvesvaraya Technological University       9677
33                                  Xidian University       9667
34                    Seoul National University (SNU)       9542
35                   National Taiwan University (NTU)       9466
36                                 Harvard University       9449
37                                 Nanjing University       9427
38        Massachusetts Institute of Technology (MIT)       9396
39                                   Korea University       9197
40        South China University of Technology (SCUT)       9192
41                  Chinese Academy of Sciences (CAS)       8989
42                                            YouTube       8822
43                      Sun Yat-Sen University (SYSU)       8610
44                                  Tongji University       8587
45                   San Jose State University (SJSU)       8274
46                                Shenzhen University       8011
47                                   Fudan University       7986
48                    Georgia Institute of Technology       7878
49                                Shandong University       7854

In [52]:

con.execute("""
SELECT country, region, sub_region, territory, zone, COUNT(*) AS rows
FROM contact_clean
GROUP BY 1,2,3,4,5
ORDER BY rows DESC
LIMIT 50
""").fetchdf()

,country,region,sub_region,territory,zone,rows
0,United States,NALA,US & Canada,null,US & Canada,1596732
1,China,APAC,China,null,China,1539154
2,India,APAC,India,SOUTH ASIA,India,1111879
3,null,null,null,null,null,804111
4,"Korea, Republic of",APAC,South Korea,null,South Korea,278575
5,Japan,APAC,Japan,null,Japan,262327
6,Germany,EMEA,Europe,DACH,Western Europe,238016
7,United Kingdom,EMEA,Europe,UK_NORDICS,Western Europe,209229
8,Taiwan,APAC,Taiwan,null,Taiwan,197293
9,Canada,NALA,US & Canada,null,US & Canada,147395
10,France,EMEA,Europe,FRANCE_BENELUX,Western Europe,147286
11,Brazil,NALA,LatAm,LA,LatAm,143200
12,Russian Federation,EMEA,Europe,RUSSIA,Russia,140301
13,Hong Kong,APAC,China,null,China,120823
14,China,APAC,China,NaN,China,105382
15,Spain,EMEA,Europe,IBERIA,Western Europe,96007
16,Indonesia,APAC,ROAP,null,SEA,94893
17,United States,NALA,US & Canada,NaN,US & Canada,91606
18,Turkey,EMEA,Europe,TURKEY,Rest of Europe,91227
19,Australia,APAC,ROAP,null,ANZ,78248
20,Poland,EMEA,Europe,POLAND_BALTICS,Eastern Europe,77022
21,Italy,EMEA,Europe,ITALY_GREECE_ISRAEL,Western Europe,75084
22,Viet Nam,APAC,ROAP,null,SEA,74410
23,Israel,EMEA,Israel,ITALY_GREECE_ISRAEL,Israel,72192
24,Singapore,APAC,ROAP,null,SEA,69826
25,The Netherlands,EMEA,Europe,FRANCE_BENELUX,Western Europe,61465
26,Mexico,NALA,LatAm,LA,LatAm,60238
27,Nigeria,EMEA,Africa,AFRICA,Africa,47876
28,Egypt,EMEA,Africa,MIDDLE EAST,Africa,45846
29,Pakistan,APAC,ROAP,SOUTH ASIA,South Asia,42061
30,Ukraine,EMEA,Europe,UKRAINE,Eastern Europe,41222
31,Philippines,APAC,ROAP,null,SEA,40984
32,Sweden,EMEA,Europe,UK_NORDICS,Nordic,40497
33,Thailand,APAC,ROAP,null,SEA,36690
34,Switzerland,EMEA,Europe,DACH,Western Europe,35298
35,Colombia,NALA,LatAm,LA,LatAm,35053
36,Malaysia,APAC,ROAP,null,SEA,33883
37,Tunisia,EMEA,Africa,AFRICA,Africa,33282
38,Argentina,NALA,LatAm,LA,LatAm,32264
39,Japan,APAC,Japan,NaN,Japan,30175
40,Afghanistan,EMEA,Middle East,MIDDLE EAST,Middle East,29351
41,Belgium,EMEA,Europe,FRANCE_BENELUX,Western Europe,27303
42,Romania,EMEA,Europe,ROMANIA_CROATIA_BULGARIA_SERBIA_REST OF BALKANS,Eastern Europe,27271
43,"Korea, Republic of",APAC,South Korea,NaN,South Korea,27177
44,Saudi Arabia,EMEA,Middle East,MIDDLE EAST,Middle East,26529
45,Austria,EMEA,Europe,DACH,Western Europe,26365
46,United Arab Emirates,EMEA,Middle East,MIDDLE EAST,Middle East,26341
47,Bangladesh,APAC,ROAP,SOUTH ASIA,South Asia,26221
48,Chile,NALA,LatAm,LA,LatAm,22886
49,Portugal,EMEA,Europe,IBERIA,Western Europe,22768


### Suggested anomaly follow-ups
Use the observations above to document findings such as:

- developers with very high activity scores but narrow activity diversity
- silent adopters who appear only in download behavior
- countries mapped inconsistently to regions or zones
- organization fields with excessive "Not Normalized" values
- duplicated activity records caused by event form design or source extraction logic


## 12. Segmentation analysis roadmap
The project can support several segmentation lenses. Start simple, then combine them.


### Segmentation families

**Engagement depth segmentation**
- low, medium, high total activity score
- number of distinct activity categories
- recency and frequency of touchpoints

**Journey type segmentation**
- event-heavy developers
- training-heavy developers
- community contributors
- product download oriented developers
- one-time explorers versus repeat engagers

**Account and geography segmentation**
- enterprise versus startup versus university
- region and zone differences
- normalized versus non-normalized organizations

**Adoption propensity segmentation**
- activity-rich developers with product download signals
- activity-rich developers with no clear adoption signals
- low-touch developers with concentrated product behavior

In [53]:

con.execute("""
WITH scored AS (
    SELECT
        dev_contact,
        SUM(COALESCE(activity_score, 0)) AS total_score,
        COUNT(*) AS total_rows,
        COUNT(DISTINCT activity) AS distinct_activities
    FROM activity_clean
    GROUP BY 1
), bucketed AS (
    SELECT
        *,
        NTILE(4) OVER (ORDER BY total_score) AS score_quartile
    FROM scored
)
SELECT score_quartile,
       COUNT(*) AS developers,
       AVG(total_score) AS avg_total_score,
       AVG(total_rows) AS avg_rows,
       AVG(distinct_activities) AS avg_distinct_activities
FROM bucketed
GROUP BY 1
ORDER BY 1
""").fetchdf()

100% ▕██████████████████████████████████████▏ (00:00:02.01 elapsed)

,score_quartile,developers,avg_total_score,avg_rows,avg_distinct_activities
0,1,1915070,1.184688,4.000105,1.161261
1,2,1915070,4.024865,2.027993,1.829085
2,3,1915070,10.639530,3.989583,2.276549
3,4,1915069,108.749412,26.193817,2.540493


## 13. Asset impact analysis candidates
These analyses move from description toward causal or quasi-causal business storytelling.


Potential extensions:
1. Measure whether selected assets are associated with increased downstream activity score in the next 30, 60, or 90 days.
2. Compare behavior before and after a webinar, DLI training, or hackathon.
3. Identify which activity names are most associated with follow-up multi-touch engagement.
4. Build developer-level event sequences and common journey paths.

In [54]:

# Example starter query for pre/post asset analysis.
asset_name = None  # Replace with an activity_name of interest.

if asset_name:
    query = f"""
    WITH asset_users AS (
        SELECT dev_contact, MIN(activity_date) AS first_asset_date
        FROM activity_clean
        WHERE activity_name = '{asset_name}'
        GROUP BY 1
    )
    SELECT
        COUNT(DISTINCT a.dev_contact) AS developers,
        AVG(CASE WHEN a.activity_date < u.first_asset_date THEN 1 ELSE 0 END) AS pre_asset_row_share,
        AVG(CASE WHEN a.activity_date > u.first_asset_date THEN 1 ELSE 0 END) AS post_asset_row_share
    FROM activity_clean a
    JOIN asset_users u
        ON a.dev_contact = u.dev_contact
    """
    display(con.execute(query).fetchdf())
else:
    print("Set asset_name to evaluate a specific asset.")

Set asset_name to evaluate a specific asset.

In [56]:
con.close()


## 14. Data enrichment plan ideas
This section is for the final deliverable around missing context and external supplementation.


Possible enrichment opportunities:
- standardize organization names and websites using external company matching logic
- enrich country and organization with market maturity or industry metadata
- classify activity names into a cleaner asset taxonomy
- enrich sdk_name or PRODUCTNAME into product families
- identify developer lifecycle stage from first and last activity windows