April

In [ ]:
import duckdb

In [2]:
con = duckdb.connect("Data/project.duckdb")
con.execute("SET temp_directory='C:/Users/antar/Spring2026_IndustryProject/duckdb_tmp'")

In [3]:
display(con.execute("SHOW TABLES").fetchdf())

                 name
0      activity_clean
1        activity_raw
2       contact_clean
3         contact_raw
4  sdk_download_clean
5    sdk_download_raw

### Analysis for `DEVPM_8674_Cal_Poly_Export_dev_activity.csv`

In [4]:
con.execute("SELECT COUNT(*) FROM activity_clean").fetchdf()

   count_star()
0      69347526

In [5]:
con.execute("""SELECT column_name
FROM information_schema.columns
WHERE table_name = 'activity_raw'""").fetchdf()

               column_name
0                 activity
1            activity_date
2            activity_name
3            activity_type
4            activity_role
5      activity_attendance
6              dev_contact
7           activity_score
8                 filepath
9              activity_id
10                     pk1
11                     pk2
12             lead_source
13      nvidia_campaign_id
14  gtc_nvidia_campaign_id
15     lead_source_details

In [6]:
con.execute("SUMMARIZE activity_clean").fetchdf()

               column_name column_type  ...     count null_percentage
0              dev_contact     VARCHAR  ...  69347526            0.00
1                 activity     VARCHAR  ...  69347526            0.00
2            activity_name     VARCHAR  ...  69347526            7.12
3            activity_type     VARCHAR  ...  69347526            0.00
4            activity_role     VARCHAR  ...  69347526           13.20
5      activity_attendance     VARCHAR  ...  69347526           81.36
6           activity_score      DOUBLE  ...  69347526            1.31
7            activity_date   TIMESTAMP  ...  69347526            0.00
8              activity_id     VARCHAR  ...  69347526            0.00
9                 filepath     VARCHAR  ...  69347526           22.16
10                     pk1     VARCHAR  ...  69347526            0.00
11                     pk2     VARCHAR  ...  69347526            0.17
12             lead_source     VARCHAR  ...  69347526           82.81
13      nvidia_campaign_id     VARCHAR  ...  69347526           98.99
14  gtc_nvidia_campaign_id     VARCHAR  ...  69347526          100.00
15     lead_source_details     VARCHAR  ...  69347526           84.02

[16 rows x 12 columns]

In [7]:
con.execute("""
SELECT activity_name, COUNT(*) AS count
FROM activity_raw
GROUP BY activity_name
ORDER BY count DESC
""").fetchdf()

                                            activity_name     count
0                                             JetPack SDK  10316702
1                                                   cuDNN   8242287
2                                                 jetpack   7365167
3                                               Developer   6527784
4                                                    None   4940143
...                                                   ...       ...
231251                            api-instance-k8s-871853         1
231252                    tonality-styled-closure-cowbird         1
231253                           genomics-analysis-1eb2d1         1
231254                                         dn-pytorch         1
231255  GPU Unix Graphics: Linux: Unmet dependencies -...         1

[231256 rows x 2 columns]

In [8]:
con.execute("""
SELECT activity_type, COUNT(*) AS count
FROM activity_clean
GROUP BY activity_type
ORDER BY count DESC
""").fetchdf()

             activity_type     count
0                Installer  36999321
1                 Approved   6654555
2   API Catalog Hosted API   6466203
3                Container   5345238
4            Documentation   1791479
..                     ...       ...
59                    true         3
60                    None         3
61                   image         3
62                  NVINFO         2
63                Document         2

[64 rows x 2 columns]

In [9]:
con.execute("""
SELECT activity_score, COUNT(*) AS count
FROM activity_clean
GROUP BY activity_score
ORDER BY count DESC
""").fetchdf()

    activity_score     count
0              3.0  40386220
1              1.0  10136402
2              0.0   7304120
3              5.0   5173631
4             10.0   1907972
5             20.0   1435932
6              NaN    906358
7              6.0    635828
8              4.0    569597
9             40.0    498176
10             2.0    150807
11             8.0    143233
12            15.0     77497
13           100.0     21750
14        948905.0         1
15        949156.0         1
16        949763.0         1

In [10]:
con.execute("""
SELECT dev_contact, COUNT(*) AS count
FROM activity_clean
GROUP BY dev_contact
ORDER BY count DESC
""").fetchdf()

        dev_contact    count
0           5903679  2027375
1           5886356   789400
2           3931685   187095
3           1303597   151947
4           2028858   142980
...             ...      ...
7660274     8296803        1
7660275     9953551        1
7660276     2891920        1
7660277     9909393        1
7660278    10473017        1

[7660279 rows x 2 columns]

In [11]:
# Check duplicates (replace with primary key if known)
display(con.execute("""
SELECT 
    COUNT(*) AS total_rows,
    COUNT(*) - (
        SELECT COUNT(*)
        FROM (SELECT DISTINCT * FROM activity_clean)
    ) AS duplicate_rows
FROM activity_clean
""").fetchdf())

   total_rows  duplicate_rows
0    69347526          163735

### Analysis for `DEVPM_8674_Cal_Poly_Export_dev_contact.csv`

In [12]:
con.execute("SELECT COUNT(*) FROM contact_clean").fetchdf()

   count_star()
0       8903197

In [13]:
con.execute("SELECT DISTINCT developer_id FROM contact_clean").fetchdf()

        developer_id
0            6911185
1            7264101
2            7679199
3            9029726
4            9787972
...              ...
8903192      3873633
8903193       428482
8903194      5140285
8903195      5220165
8903196      2847519

[8903197 rows x 1 columns]

In [14]:
con.execute("""SELECT column_name
FROM information_schema.columns
WHERE table_name = 'contact_clean'""").fetchdf()

                        column_name
0                      developer_id
1        program_application_source
2                           country
3                            region
4                        sub_region
5                              zone
6                         territory
7         organization_english_name
8                 development_areas
9           other_development_areas
10        industry_segment_vertical
11  other_industry_segment_vertical
12    sub_industry_segment_vertical
13               fields_of_interest
14         other_fields_of_interest
15   first_program_application_date
16                       account_id
17                     account_name
18               last_activity_date
19               last_modified_date
20                     created_date
21                    wwfo_category
22                 wwfo_target_list
23         account_industry_segment
24                   account_source
25                     account_type
26          devzone_last_login_date
27             organization_website
28                     inception_id
29              first_activity_date
30          normalized_account_name
31                    rdp_exit_date

In [15]:
con.execute("SUMMARIZE contact_clean").fetchdf()

                        column_name column_type  ...    count null_percentage
0                      developer_id     VARCHAR  ...  8903197            0.00
1        program_application_source     VARCHAR  ...  8903197            0.00
2                           country     VARCHAR  ...  8903197            0.00
3                            region     VARCHAR  ...  8903197            0.00
4                        sub_region     VARCHAR  ...  8903197            0.00
5                              zone     VARCHAR  ...  8903197            0.00
6                         territory     VARCHAR  ...  8903197            0.00
7         organization_english_name     VARCHAR  ...  8903197            0.00
8                 development_areas     VARCHAR  ...  8903197            0.00
9           other_development_areas     VARCHAR  ...  8903197            0.00
10        industry_segment_vertical     VARCHAR  ...  8903197            0.00
11  other_industry_segment_vertical     VARCHAR  ...  8903197            0.02
12    sub_industry_segment_vertical     VARCHAR  ...  8903197            0.00
13               fields_of_interest     VARCHAR  ...  8903197            0.00
14         other_fields_of_interest     VARCHAR  ...  8903197            0.00
15   first_program_application_date   TIMESTAMP  ...  8903197           29.05
16                       account_id     VARCHAR  ...  8903197            0.00
17                     account_name     VARCHAR  ...  8903197            0.00
18               last_activity_date   TIMESTAMP  ...  8903197           17.97
19               last_modified_date   TIMESTAMP  ...  8903197            0.00
20                     created_date   TIMESTAMP  ...  8903197            0.00
21                    wwfo_category     VARCHAR  ...  8903197            0.00
22                 wwfo_target_list     VARCHAR  ...  8903197            0.00
23         account_industry_segment     VARCHAR  ...  8903197            0.00
24                   account_source     VARCHAR  ...  8903197            0.00
25                     account_type     VARCHAR  ...  8903197           68.01
26          devzone_last_login_date   TIMESTAMP  ...  8903197           49.65
27             organization_website     VARCHAR  ...  8903197            0.00
28                     inception_id     VARCHAR  ...  8903197            0.00
29              first_activity_date   TIMESTAMP  ...  8903197           17.97
30          normalized_account_name     VARCHAR  ...  8903197            0.00
31                    rdp_exit_date   TIMESTAMP  ...  8903197          100.00

[32 rows x 12 columns]

In [17]:
# Check duplicates (replace with primary key if known)
display(con.execute("""
SELECT 
    COUNT(*) AS total_rows,
    COUNT(*) - (
        SELECT COUNT(*)
        FROM (SELECT DISTINCT * FROM contact_clean)
    ) AS duplicate_rows
FROM contact_clean
""").fetchdf())

   total_rows  duplicate_rows
0     8903197               0

### Analysis for `DEVPM_8674_Cal_Poly_Export_sdk_download.csv`

In [18]:
con.execute("SELECT COUNT(*) FROM sdk_download_clean").fetchdf()

   count_star()
0      93038213

In [19]:
con.execute("""SELECT column_name
FROM information_schema.columns
WHERE table_name = 'sdk_download_raw'""").fetchdf()

        column_name
0            source
1          sdk_name
2       PRODUCTNAME
3    PRODUCTRELEASE
4           country
5            region
6         subregion
7         territory
8              zone
9      downloaddate
10         FILETYPE
11  OPERATINGSYSTEM
12  OS_DISTRIBUTION
13     ARCHITECTURE
14              KPI
15    downloadcount

In [20]:
con.execute("SUMMARIZE sdk_download_clean").fetchdf()

         column_name column_type                                 min  ...         q75     count null_percentage
0             source     VARCHAR                                 CDN  ...        None  93038213            0.00
1           sdk_name     VARCHAR                              3DGRUT  ...        None  93038213            1.37
2       product_name     VARCHAR  (Linux) Acoustic Echo Cancellation  ...        None  93038213            0.00
3    product_release     VARCHAR                                 0.0  ...        None  93038213            1.39
4            country     VARCHAR                                  AD  ...        None  93038213            1.35
5             region     VARCHAR                                APAC  ...        None  93038213            1.35
6          subregion     VARCHAR                              Africa  ...        None  93038213            1.35
7          territory     VARCHAR                              AFRICA  ...        None  93038213           42.43
8               zone     VARCHAR                                 ANZ  ...        None  93038213            1.35
9      download_date        DATE                          2020-01-01  ...  2025-07-24  93038213            0.00
10         file_type     VARCHAR                                   ?  ...        None  93038213            1.29
11  operating_system     VARCHAR                                 AIX  ...        None  93038213           19.29
12   os_distribution     VARCHAR                                 1.0  ...        None  93038213           94.56
13      architecture     VARCHAR                                 ARM  ...        None  93038213           94.74
14               kpi      DOUBLE                                 0.0  ...         1.0  93038213            1.00
15    download_count      BIGINT                             -449443  ...           7  93038213            0.00

[16 rows x 12 columns]

In [21]:
# Check duplicates (replace with primary key if known)
display(con.execute("""
SELECT 
    COUNT(*) AS total_rows,
    COUNT(*) - (
        SELECT COUNT(*)
        FROM (SELECT DISTINCT * FROM sdk_download_clean)
    ) AS duplicate_rows
FROM sdk_download_clean
""").fetchdf())

   total_rows  duplicate_rows
0    93038213          275400