In [4]:
import duckdb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

DB_PATH = "developer_project.duckdb"
con = duckdb.connect(DB_PATH)

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 100)

ACTIVITY_TABLE = "activity_final"
CONTACT_TABLE = "contact_final"

In [5]:
con.execute("""SHOW TABLES""").fetchdf()

                             name
0                activity_base_v2
1          activity_dictionary_v2
2   activity_effort_mapping_ai_v2
3                  activity_final
4             activity_labeled_v2
5            activity_ontology_v2
6                    activity_raw
7                   contact_final
8              contact_one_row_v2
9                     contact_raw
10         contact_supplement_raw
11              dev_activation_v2
12         dev_contact_persona_v2
13         dev_dormancy_status_v2
14            dev_effort_level_v2
15          dev_features_0_30d_v2
16         dev_features_30_90d_v2
17        dev_features_90_180d_v2
18       dev_features_lifetime_v2
19           dev_journey_state_v2
20         dev_meaningful_week_v2
21                 dev_persona_v2
22           dev_profile_final_v4
23        dev_recency_features_v2
24         dev_weekly_features_v2
25          developer_universe_v2
26             sdk_download_final
27               sdk_download_raw

In [6]:
con.execute("""
SELECT
    persona,
    COUNT(*) AS cnt,
    COUNT(*) * 1.0 / SUM(COUNT(*)) OVER () AS pct
FROM dev_persona_v2
GROUP BY 1
ORDER BY cnt DESC
""").fetchdf()

              persona      cnt       pct
0                CUDA  3519981  0.375204
1               GenAI  2314671  0.246727
2             Unknown  1869569  0.199282
3            Robotics   590804  0.062975
4          Simulation   570051  0.060763
5  Learning_Community   516432  0.055048

In [8]:
con.execute("""
SELECT COUNT(*)
FROM dev_features_lifetime_v2
WHERE lifetime_activity_count = 0
""").fetchdf()

   count_star()
0       1721230

In [10]:
con.execute("""
SELECT *
FROM activity_ontology_v2
WHERE persona_hint = 'Other'
LIMIT 100

""").fetchdf()

,developer_id,activity_date,activity,activity_name,activity_type,activity_role,activity_attendance,activity_score,filepath,lead_source,lead_source_details,nvidia_campaign_id,keyword_text,persona_activity_text,cuda_activity_score,genai_activity_score,robotics_activity_score,simulation_activity_score,learning_community_activity_score,journey_signal,effort_level,persona_hint,cuda_persona_score,genai_persona_score,robotics_persona_score,simulation_persona_score,learning_community_persona_score,modality
0,6790671,2024-05-30,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
1,1257703,2021-05-13,dli training,data augmentation and segmentation with genera...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,data augmentation and segmentation with genera...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
2,6878674,2024-06-19,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
3,6785420,2024-05-29,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
4,2107115,2024-04-18,dli training,accelerating end-to-end data science workflows...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,accelerating end-to-end data science workflows...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
5,7080178,2024-08-10,dli training,integrating sensors with nvidia drive®,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,integrating sensors with nvidia drive® unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
6,3037476,2024-06-20,dli training,introduction to graph neural networks,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,introduction to graph neural networks unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
7,6962400,2024-07-11,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
8,6891390,2024-06-22,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
9,6803979,2024-06-03,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
10,6893662,2024-06-22,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
11,6805929,2024-06-04,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
12,7061133,2024-08-05,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
13,6585889,2024-06-04,dli training,introduction to transformer-based natural lang...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,introduction to transformer-based natural lang...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
14,6441297,2024-07-25,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
15,6810317,2024-06-04,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
16,6292258,2024-06-05,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,ref-dev-500409,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
17,8902499,2025-05-29,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
18,6587967,2024-08-07,dli training,[access expires 07/24/2026] deploying a model ...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,[access expires 07/24/2026] deploying a model ...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
19,4465277,2024-08-07,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
20,5913271,2020-08-25,dli training,developing scalable iva applications using dee...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,developing scalable iva applications using dee...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
21,6988519,2024-08-08,dli training,introduction to transformer-based natural lang...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,introduction to transformer-based natural lang...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
22,6845110,2024-06-11,dli training,introduction to transformer-based natural lang...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,introduction to transformer-based natural lang...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
23,6426572,2024-06-11,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
24,5524486,2024-08-08,dli training,introduction to transformer-based natural lang...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,introduction to transformer-based natural lang...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
25,6996137,2024-07-19,dli training,introduction to transformer-based natural lang...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,introduction to transformer-based natural lang...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
26,6497744,2024-08-09,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
27,5896163,2024-08-09,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
28,7053842,2024-08-03,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
29,6992263,2024-08-10,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
30,2025877,2024-08-26,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
31,7131145,2024-08-24,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
32,5877871,2024-08-27,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
33,3547828,2024-08-26,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
34,5945667,2024-07-06,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
35,6844337,2024-06-17,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
36,8967236,2025-05-29,dli training,accelerating end-to-end data science workflows,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,accelerating end-to-end data science workflows...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
37,6089252,2024-05-07,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
38,7408475,2024-10-19,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
39,7410214,2024-10-19,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
40,7233406,2024-09-16,dli training,accelerating end-to-end data science workflows...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,accelerating end-to-end data science workflows...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
41,7574193,2024-11-19,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
42,7236706,2024-09-16,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
43,4289477,2024-09-16,dli training,[access expires 07/24/2026] deploying a model ...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,[access expires 07/24/2026] deploying a model ...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
44,5034035,2024-08-07,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
45,7029779,2024-08-08,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
46,4740414,2024-08-08,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
47,6017311,2024-08-08,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
48,7239206,2024-09-16,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
49,7238072,2024-09-16,dli training,introduction to transformer-based natural lang...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,introduction to transformer-based natural lang...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
50,6887814,2024-09-02,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
51,7238020,2024-09-16,dli training,[access expires 07/24/2026] deploying a model ...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,[access expires 07/24/2026] deploying a model ...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
52,7239755,2024-09-17,dli training,[access expires 07/24/2026] deploying a model ...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,[access expires 07/24/2026] deploying a model ...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
53,7415067,2024-10-20,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
54,7237086,2024-09-17,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
55,7242463,2024-09-17,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
56,7415934,2024-10-20,dli training,prompt engineering with llama-2 (access expire...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,prompt engineering with llama-2 (access expire...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
57,5278817,2024-09-04,dli training,building real-time video ai applications,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,building real-time video ai applications unknown,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
58,6155602,2024-09-04,dli training,[access expires 07/24/2026] deploying a model ...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,[access expires 07/24/2026] deploying a model ...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training
59,7188878,2024-09-05,dli training,modeling time series data with recurrent neura...,self-paced online,attendee,attended live,20.0,None,unknown,unknown,NaN,dli training self-paced online attendee attend...,modeling time series data with recurrent neura...,0.0,0.0,0.0,0.0,0.0,Learn,Moderate,Other,0.0,0.0,0.0,0.0,0.0,Training

In [11]:
con.execute("""
SELECT activity, COUNT(*)
FROM activity_ontology_v2
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY COUNT(*) DESC

""").fetchdf()

                  activity  count_star()
0        devzone downloads       6713745
1                model api       6143796
2   dev program membership       5828134
3            ngc downloads       3282428
4             dli training        446049
5               conference        184016
6                 webinars        123680
7      conf. sessions live        123025
8     program applications        122320
9                     brev        100847
10              bugs filed         70920
11           user feedback         56723
12     forum contributions         51393
13         on-demand views         16506
14  product specific comms         11348
15            other events          8001
16     event registrations          5651
17                contests          1416
18              hackathons           801

In [12]:
con.execute("""
SELECT
    activity_name,
    COUNT(*) AS cnt
FROM activity_ontology_v2
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY cnt DESC
LIMIT 50

""").fetchdf()

                            activity_name      cnt
0                               developer  5682594
1                                 jetpack  2662961
2                                 unknown  1796141
3                                   other  1090625
4                              sdkmanager   474474
5                              deepstream   462659
6                          ai-deepseek-r1   427318
7                        ai-deepseek-v3_1   411394
8             texture tools for photoshop   395573
9                            ai-kimi-k2_5   371072
10                              ai-glm4_7   295417
11                       ai-deepseek-v3_2   255790
12                      nvidia gpu driver   235762
13                     ai-qwen3-235b-a22b   205146
14                        ai-minimax-m2_1   196592
15              ai-deepseek-v3_1-terminus   193386
16                                  drive   178663
17             ai-llama-3_1-405b-instruct   172744
18               ai-llama-3_1-8b-instruct   172027
19                    ai-deepseek-r1-0528   169194
20                    ai-kimi-k2-instruct   153922
21              ai-llama-3_1-70b-instruct   152069
22                                ai-glm5   150653
23               ai-kimi-k2-instruct-0905   147483
24  gpu technology conference spring 2021   146078
25                        ai-gpt-oss-120b   140645
26                    ai-kimi-k2-thinking   112522
27                     riva speech skills   111311
28         texture tools - standalone app   110519
29                            jetpack l4t   107618
30              ai-llama-3_3-70b-instruct   105054
31                             ai-qwq-32b   102736
32                       ai-orangina-120b   101312
33                        ai-orangina-20b    99009
34                            jetpack-l4t    94714
35                            gxf runtime    90996
36                          texture tools    89747
37         building a brain in 10 minutes    89079
38  ai-llama-4-maverick-17b-128e-instruct    86241
39                   ai-qwen3_5-397b-a17b    85154
40         ai-qwen3-next-80b-a3b-instruct    84540
41      ai-qwen3-coder-480b-a35b-instruct    84284
42                         nvidia riva ea    75379
43                         classification    71473
44               nvidia container toolkit    67792
45                           ai-llama3-8b    64429
46                                    l4t    63555
47                          ai-llama3-70b    63361
48                              drive sdk    58070
49                        ai-minimax-m2_5    57685

In [13]:
con.execute("""
SELECT
    filepath,
    COUNT(*) AS cnt
FROM activity_ontology_v2
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY cnt DESC
LIMIT 50
""").fetchdf()

                                             filepath      cnt
0                                                 NaN  7147903
1                854db4e5-9be7-45a0-a730-183cadf87e50   427318
2                e723ebf1-2d74-4b1e-b744-52dd9355d1dd   359013
3                3e0e9d6f-e178-4ec7-af95-f6a612552edc   307801
4                7803a8e0-ea2a-4303-89b5-fb1285300952   295417
5                6804929c-30da-4f1b-ba44-a185a28cd6bd   255790
6                5a3a2b46-a598-48f4-a942-d4b2704bc558   205146
7                02f30544-5413-47d1-a753-dc55b824355d   196592
8                853b883c-b3ae-41bc-aa2d-b147389f6490   193386
9                e62a4350-2218-4cf5-9262-112432d239f8   172027
10               4e527eb9-d178-4f4d-9976-a1adf343df3a   169194
11               ef4c64a3-ac60-4fd9-8ade-4c532e9c2365   153922
12               8f723982-f99d-4978-a0cb-1334163e0e07   152069
13               812b8087-37f1-4c7b-854f-8d610a8cf4d4   150653
14               fe39b6a0-7a42-4643-bac2-3905e36e25c8   147483
15               7c79b6d5-3552-41e7-8574-c4d431548d8e   142701
16               9fcd3abb-183b-4ef0-b884-663507e5e66e   140645
17  verizon://sdkmanager/secure/clients/sdkmanager...   138239
18               2cf148f4-c92b-4266-8745-dfc36eb06ea8   112522
19  /designworks/texture-tools-for-photoshop/secur...   111676
20  verizon://designworks/texture-tools-for-photos...   109533
21               84eb5de1-166b-4bb4-a01b-4f51bd90aa52   105054
22               73c42196-667b-4292-a9bb-589593826e84   103593
23               ad2a0a99-910d-448f-8006-2eb942b3b9f2   102736
24               50a713bb-aff9-4e4a-bc2e-28dea8240a3f   101312
25               3856e52c-2635-4fb9-bb2b-3643d67eb9fe    99009
26               2f092df4-a732-4e88-b3a9-337829a9cde7    86241
27               f32596d4-0577-4a17-baf2-034515d1e457    85154
28               e467a0f2-c74f-4c21-8bf8-b977d7895f93    84540
29               7ce8beeb-bdce-472a-a8ac-d128be27118f    84284
30  verizon://assets/embedded/secure/tools/files/j...    78645
31  verizon://sdkmanager/secure/clients/sdkmanager...    77815
32  verizon://designworks/texture-tools-for-photos...    66078
33               a5a3ad64-ec2c-4bfc-8ef7-5636f26630fe    64429
34  /designworks/texture-tools-for-photoshop/secur...    59146
35               da9660c1-f121-46f7-ae2a-9ae22b727284    57685
36  verizon://assets/embedded/secure/tools/files/j...    56803
37               1dfe75d1-a4ce-4eee-ba37-c3df1ce13f7b    56725
38               24d90582-d41c-4fc6-adc0-53c97f5a710f    53570
39  /assets/secure/shadermodel6-9-preview-driver/5...    53170
40  verizon://assets/embedded/secure/tools/files/j...    48784
41               c64334de-a2b5-49bf-b477-af9d8e86af06    48652
42               a88f115a-4a47-4381-ad62-ca25dc33dc1b    46815
43  /sdkmanager/secure/clients/sdkmanager-2.2.0.12...    46535
44  verizon://assets/embedded/secure/tools/files/j...    46211
45  verizon://designworks/texture-tools-for-photos...    45551
46  verizon://assets/embedded/secure/tools/files/j...    44879
47  verizon://assets/embedded/secure/tools/files/j...    42807
48               373b69a3-3c04-4297-a789-f3a948c95aed    41857
49               710c92d0-7c98-46d6-b5ae-07e84bcaa5d3    41402

In [14]:
con.execute("""
SELECT
    AVG(total_persona_score),
    MIN(total_persona_score),
    MAX(total_persona_score)
FROM dev_persona_v2
""").fetchdf()

,avg(total_persona_score),min(total_persona_score),max(total_persona_score)
0,32.389397,0.0,10547644.0

In [15]:
con.execute("""
SELECT
    activity_name,
    COUNT(*) AS cnt
FROM activity_ontology_v2
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY cnt DESC
LIMIT 100
""").fetchdf()

                                        activity_name      cnt
0                                           developer  5682594
1                                             jetpack  2662961
2                                             unknown  1796141
3                                               other  1090625
4                                          sdkmanager   474474
5                                          deepstream   462659
6                                      ai-deepseek-r1   427318
7                                    ai-deepseek-v3_1   411394
8                         texture tools for photoshop   395573
9                                        ai-kimi-k2_5   371072
10                                          ai-glm4_7   295417
11                                   ai-deepseek-v3_2   255790
12                                  nvidia gpu driver   235762
13                                 ai-qwen3-235b-a22b   205146
14                                    ai-minimax-m2_1   196592
15                          ai-deepseek-v3_1-terminus   193386
16                                              drive   178663
17                         ai-llama-3_1-405b-instruct   172744
18                           ai-llama-3_1-8b-instruct   172027
19                                ai-deepseek-r1-0528   169194
20                                ai-kimi-k2-instruct   153922
21                          ai-llama-3_1-70b-instruct   152069
22                                            ai-glm5   150653
23                           ai-kimi-k2-instruct-0905   147483
24              gpu technology conference spring 2021   146078
25                                    ai-gpt-oss-120b   140645
26                                ai-kimi-k2-thinking   112522
27                                 riva speech skills   111311
28                     texture tools - standalone app   110519
29                                        jetpack l4t   107618
30                          ai-llama-3_3-70b-instruct   105054
31                                         ai-qwq-32b   102736
32                                   ai-orangina-120b   101312
33                                    ai-orangina-20b    99009
34                                        jetpack-l4t    94714
35                                        gxf runtime    90996
36                                      texture tools    89747
37                     building a brain in 10 minutes    89079
38              ai-llama-4-maverick-17b-128e-instruct    86241
39                               ai-qwen3_5-397b-a17b    85154
40                     ai-qwen3-next-80b-a3b-instruct    84540
41                  ai-qwen3-coder-480b-a35b-instruct    84284
42                                     nvidia riva ea    75379
43                                     classification    71473
44                           nvidia container toolkit    67792
45                                       ai-llama3-8b    64429
46                                                l4t    63555
47                                      ai-llama3-70b    63361
48                                          drive sdk    58070
49                                    ai-minimax-m2_5    57685
50                                      ai-minimax-m2    56725
51                                               misc    53786
52                                     ai-gpt-oss-20b    53570
53                             texture tools exporter    49550
54                                        nvidia riva    49491
55                                  ai-step-3_5-flash    48652
56                    nvidia kubernetes device plugin    45732
57                                  codeworks android    44642
58              ai-mistral-large-3-675b-instruct-2512    41857
59                          ai-mixtral-8x22b-instruct    41402
60                                           rivermax    39519
61                                     gameworks-misc    38284
62                                  ai-gemma-3-27b-it    38063
63                                        tao toolkit    37785
64                     ai-qwen3-next-80b-a3b-thinking    35965
65                                ai-nv-embedqa-e5-v5    33860
66  building transformer-based natural language pr...    33533
67                                             shield    33455
68                           ai-mixtral-8x7b-instruct    31756
69                                               doca    30675
70   disaster risk monitoring using satellite imagery    30268
71                             ai-qwen2_5-7b-instruct    30040
72                                ai-evo2-40b-forward    28911
73  accelerate data science workflows with zero co...    28601
74                                        ai-gemma-7b    28382
75                      ai-qwen2_5-coder-32b-instruct    25890
76                    ai-deepseek-r1-distill-qwen-32b    25268
77                   ai-devstral-2-123b-instruct-2512    25095
78                                   nvidia jarvis ea    24980
79               nvidia driver manager for kubernetes    24628
80                                          ai-bge-m3    23559
81                                      ai-embed-qa-4    23522
82                         nvidia vgpu guest driver 6    23028
83                         ai-mistral-7b-instruct-v03    22433
84                                 ai-evo2-7b-forward    22370
85                  ai-llama-4-scout-17b-16e-instruct    22348
86                            nvidia doca-ofed driver    21795
87                                nvidia mofed driver    21449
88                      ai-llama-3_2-nv-embedqa-1b-v2    21353
89                                             ubuntu    21264
90                                                nlp    20607
91                                   ai-gemma-2-2b-it    20479
92                    tao toolkit for computer vision    19904
93                                             python    19647
94                                     ai-nv-embed-v1    19285
95        nvidia gpu feature discovery for kubernetes    19234
96                                  ai-gemma-2-27b-it    19085
97  [access expires 07/24/2026] getting started wi...    19077
98                                              physx    18816
99                   ai-llama-3_2-90b-vision-instruct    18799

In [16]:
con.close()